### ISSUE TITLE
renseignement

### ISSUE THREAD

**Issue by Mahora2106** [izneo-get/izneo-get#10]
Bonjour, j'ai essaye le script, mais j'ai du mal à tout comprendre. Ça me dit que la BD n'est pas dans l'abonnement. Cela fonctionne juste pour les albums présents dans l'abonnement ? Ou également avec les albums qu'on a acheté et qui sont présent dans notre bibliothèque ?

**Comment by Mahora2106** [comment]
Ah c'est bon ça fonctionné j'ai réussi. Par contre est-ce que c'est possible de mettre plusieurs albums d'un coup ? Enfin qui liste qui fait les albums les uns après les autres. 
J'ai essayé ça, mais ça pas marché, je sais pas trop si c'était pour faire ça, mais j'ai pas du comprendre comment ça fonctionnait.
Merci par avance^^

**Comment by izneo-get** [comment]
>  Cela fonctionne juste pour les albums présents dans l'abonnement ? Ou également avec les albums qu'on a acheté et qui sont présent dans notre bibliothèque ?

N'ayant malheureusement pas la possibilité de tester sur les albums achetés, je ne peux garantir que le téléchargement des BD présentes dans l'abonnement. 

> Par contre est-ce que c'est possible de mettre plusieurs albums d'un coup ?

Le script "izneo_get_selenium" permet de récupérer soit la BD présente à une URL (il faut alors mettre l'URL en dernier argument de la ligne de commande), soit une liste de BDs dont les URLs sont inscrites dans un fichier texte (il faut alors mettre le chemin du fichier en dernier argument de la ligne de commande).
Cf. https://github.com/izneo-get/izneo-get#izneo_get

Vous pouvez utiliser "izneo_list.py" qui permet de récupérer une liste d'URL. Avec la redirection dans un fichier texte, vous pouvez créer le fichier à utiliser dans "izneo_get_selenium".

**Comment by Mahora2106** [comment]
Bonjour et merci pour la réponse. Alors je confirme que cela fonctionne également avec nos albums achetés.
Pour la liste en gros je dois noté par exemple : 
izneo_get_selenium.py /list.txt
C'est bien ça ? Et je crée un fichier texte et je mets juste les url des albums les un en dessous des autres ?

**Comment by Mahora2106** [comment]
apparemment ce n'est pas comme ça, ça pas fonctionné.
J'ai bien crée un fichier texte que je n'ai nommé liste et j'ai mis dedans les urls les un en dessous des autres.
C'est la ligne de commande qui n'est pas bonne ?

**Comment by izneo-get** [comment]
Si vous appelez 
```
 izneo_get_selenium.py /list.txt
```
le script s'attend à ce que :
- le fichier s'appelle "list.txt" (et pas "liste")
- le fichier se trouve à la racine (et non pas à la racine du projet) de votre système et que vous êtes sous Linux


Si vous avez un fichier "liste.txt" qui contient 1 URL par ligne et que ce fichier se trouve au même niveau que "izneo_get_selenium.py", il faut appeler 
```
python izneo_get_selenium.py liste.txt
```

**Comment by Mahora2106** [comment]
Super ça marche. Merci beaucoup et surtout merci pour tout ce travail.

**Comment by Mahora2106** [comment]
Petite question cela fonctionne pas avec les webtoons ?

**Comment by izneo-get** [comment]
> Petite question cela fonctionne pas avec les webtoons ?

Je n'ai pas testé. 
Avez-vous une URL de webtoon inclus dans l'abonnement ?

**Comment by Mahora2106** [comment]
Normalement celui-ci y est : https://www.izneo.com/fr/webtoon/yaoi/cocoon-of-the-heart-16989

**Comment by izneo-get** [comment]
Comme c'est un sujet distinct, je propose que la discussion "webtoons" se poursuive ici : https://github.com/izneo-get/izneo-get/issues/11
