### ISSUE TITLE
Cela fonctionne-t-il avec les webtoons ?

### ISSUE THREAD

**Issue by izneo-get** [izneo-get/izneo-get#11]
Petite question cela fonctionne pas avec les webtoons ?

Normalement celui-ci y est : https://www.izneo.com/fr/webtoon/yaoi/cocoon-of-the-heart-16989

_Originally posted by @Mahora2106 in https://github.com/izneo-get/izneo-get/issues/10#issuecomment-696735950_

**Comment by Mahora2106** [comment]
Ok pas de soucis.

**Comment by izneo-get** [comment]
Les webtoons sont un format bien distinct. 
Tel quel, le script ne peut pas récupérer ce format. 
Je pense qu'il serait possible de récupérer le contenu, mais la grande question est : comment ?

Est-ce qu'il vaut mieux une énorme image ? Plusieurs images, découpées aléatoirement ?

**Comment by Mahora2106** [comment]
De base normalement elles sont découpées en plusieurs images quand je les récupérais avant leur changement.

**Comment by izneo-get** [comment]
En faisant des tests rapides, le résultat n'est pas très convaincant. 

On récupère des morceaux très hauts (plus qu'une page de BD "normale") et coupés n'importe comment.
Exemple : 
![exemple](https://i.imgur.com/f8USt4M.png)

**Comment by Mahora2106** [comment]
On récupère pas les images dans l'ordre de haut en bas ?

**Comment by Mahora2106** [comment]
Bonjour, avez-vous ressayé depuis ? Je sais que cela prend du temps etc ne vous inquiétez pas, c'est juste pour savoir^^

**Comment by izneo-get** [comment]
Bonjour,

J'avoue que pour le moment, ce n'est pas ma priorité. 
Mais je garde ce ticket ouvert pour quand j'aurai un peu de temps.

**Comment by Mahora2106** [comment]
Ok pas de souci.
Bon courage pour tout ton travail et encore merci

**Comment by mrdotb** [comment]
J'ai pas de webtoon mais essaye avec mon script sur https://github.com/izneo-get/izneo-get/issues/13
Tu ouvres la console chrome `ctrl-maj-i` tu vas sur la page du webtoon tu copies le premier script dans la console tu attends... puis le deuxième et ca devrait tout te dl proprement.

**Comment by Mahora2106** [comment]
Effectivement cela fonctionne, juste dommage qu'on doit appuyer sur entrée à chaque fois, mais heureusement les webtoons sont assez courtes.
Merci beaucoup^^

**Comment by mrdotb** [comment]
Je pense que c'est adaptable a izneo-get je vais essayer de le faire :factory_worker:

**Comment by izneo-get** [comment]
Grâce aux informations données par @mrdotb, j'ai fait une nouvelle version. 
Elle est désormais capable de récupérer les webtoons.

**Comment by Mahora2106** [comment]
Super merci beaucoup à vous deux je vais tester ça :)
