### ISSUE TITLE
Ne fonctionne plus ?

### ISSUE THREAD

**Issue by TheOneWhoKnokks** [izneo-get/izneo-get#12]
Hello,

J'ai l'impression que ça ne marche pas/plus.

J'ai essayé avec ce comics qui est inclus dans l'abonnement : https://www.izneo.com/fr/abo/comics/super-heros/batman-the-dark-knight-returns-26788 mais impossible de le récupérer. J'ai vérifié le cfduid et le session_id, les deux sont bons.

```
python3 izneo_get.py https://www.izneo.com/fr/abo/comics/super-heros/batman-the-dark-knight-returns-26788
URL: https://www.izneo.com/fr/abo/comics/super-heros/batman-the-dark-knight-returns-26788
Cette BD n'est pas disponible dans l'abonnement
ERROR Impossible de trouver le livre
Terminé !
```

**Comment by izneo-get** [comment]
Doublon de https://github.com/izneo-get/izneo-get/issues/8

Izneo a modifié la sécurité de son site. Les images sont désormais protégées et il faut utiliser une nouvelle méthode pour les récupérer.

Je vous invite à mettre à jour le projet et tester le nouveau script "izneo_get_selenium.py".
