### ISSUE TITLE
Selenium improvement

### ISSUE THREAD

**Issue by mrdotb** [izneo-get/izneo-get#13]
Salut,

Je voulais télécharger mes bd sur izneo. En regardant un peu leur code JS pour comprendre comment il decrypt les images j'ai vu qu'un objet `book` est leak sur le scope global. Dedans tu as tous les blob jpeg qui sont utilise pour dessiner sur le canvas.
J'ai écris un script pour download une bd full il faut juste être sur la page de la bd.
Je suis pas très python mais j'ai regarde un peu votre code et j'ai vu que vous faite un canvas to image.
Je pense qu'utiliser l'objet `book` est plus simple et tu recup les images raw qu'il dessine dans le canvas.

1. Charger tous les blobs
```
function pressRightArrow() {
  document.dispatchEvent(
    new KeyboardEvent("keydown", {
      keyCode: 39, // example values.
      shiftKey: false, // you don't need to include values
      ctrlKey: false,  // if you aren't going to use them.
      metaKey: false   // these are here for example's sake.
    })
  ); 
}

// On commence par charger tous les blob en allant au bout de la bd a grand coup de right arrow
for (let i = 1; i < book.pages.length; i++) {
  setTimeout(function timer() {
    pressRightArrow()
  }, i * 200);
}
```

2. Download tous les blobs
```
function downloadBlob(blob, name = 'file.txt') {
  // Convert your blob into a Blob URL (a special url that points to an object in the browser's memory)
  const blobUrl = URL.createObjectURL(blob);

  // Create a link element
  const link = document.createElement("a");

  // Set link's href to point to the Blob URL
  link.href = blobUrl;
  link.download = name;

  // Append link to the body
  document.body.appendChild(link);

  // Dispatch click event on the link
  // This is necessary as link.click() does not work on the latest firefox
  link.dispatchEvent(
    new MouseEvent('click', { 
      bubbles: true, 
      cancelable: true, 
      view: window 
    })
  );

  // Remove link from body
  document.body.removeChild(link);
}

// Ensuite on peut dl tous les blobs
for (let i = 0; i < book.pages.length; i++) {
  setTimeout(function timer() {
    downloadBlob(book.pages[i].jpeg, `${book.title}-${i + 1}.jpeg`)
  }, i * 200);
}
```
Vous pouvez check leur objet book je crois que toutes les meta data de la bd sont dedant.

**Comment by izneo-get** [comment]
Merci pour ces informations précieuses !

Récupérer les informations depuis le blob est plus compliqué en Python (il faut injecter du JS pour récupérer la valeur), mais c'est effectivement un solution qui semble plus propre car on récupère directement le jpeg du serveur, sans passer par l'équivalent d'une capture d'écran. 

Je vais regarder si je peux facilement modifier le script "isneo_get_selenium.py".

**Comment by izneo-get** [comment]
J'ai modifié le script "iszeo_get_selenium.py" afin que les images soient récupérées des blobs.
