### ISSUE TITLE
Breaking the crypto blob / remove selenium

### ISSUE THREAD

**Issue by mrdotb** [izneo-get/izneo-get#14]
J'ai continue a reverse le code de izneo.
J'arrive a decrypter leur image en local.
Quand t'arrive sur la page de la bd ils font une requete GET `https://www.izneo.com/book/:book_id`
Dans la réponse tu as la key et l'iv a utiliser pour decrypter les images et toutes les meta data.
```
"pages": [
      {
        "albumPageNumber": 0,
        "dpPageNumber": 1,
        "key": "BBlhmvYYE3MQz/Vya1w2TA==",
        "iv": "5/KTuD8xkWm62QbzxTJISg==",
        "spread": "single",
        "width": 1920,
        "height": 2690
      },
      ....]
```
Ensuite il faut dl les images encrypte sur GET `https://www.izneo.com/book/:book_id/:page_number?full`

J'ai fais un [repo](https://github.com/mrdotb/uu3cXJMu) si tu veux essayer.
Tu met la key et l'iv dans les inputs correspondante et tu charges l'image encrypte correspondante et ca te dl l'image non encrypte.

Ca peut ce porter en python avec [pycryptodome](https://github.com/Legrandin/pycryptodome) du coup tu peux faire sans selenium.
https://crypto.stackexchange.com/questions/63441/differences-between-webcrypto-js-and-cryptodome-cipher-aes-python

**Comment by izneo-get** [comment]
Super !

J'avais commencé à reverse-engineerer le code de Izneo, mais j'avais arrêté par manque de compétences en JS. 
Merci beaucoup pour les infos.

**Comment by mrdotb** [comment]
Le week-end prochain j'essaye d’écrire un code en python qui fait pareil si tu n'arrives pas a le faire d'ici la.

**Comment by izneo-get** [comment]
Pas sûr de pouvoir avancer dessus, car suite aux progrès faits dans la sauvegarde des blobs, je viens de me lancer dans la récupération des images de Cafeyn :D

**Comment by mrdotb** [comment]
D'acc j'essayerais de mon cote. L'avantage de cette solution c'est qu'Izneo pourra pas la patch facilement :smile:

**Comment by izneo-get** [comment]
J'ai utilisé ton code, mais je n'arrive pas à lui faire déchiffrer une image.
J'ai une exception "AsyncFunctionThrow" sur la ligne 
```
let decrypted = await window.crypto.subtle.decrypt(
      {
        name: "AES-CBC",
        iv: iv
      },
      rkey,
      encoded 
    );
```

De mon coté, j'ai commencé à modifier "izneo_get.py" pour qu'il récupère les informations ainsi que les images chiffrées, mais je n'arrive pas à déchiffrer les images.
La fonction "f()" du javascript permet de décoder "key" et "iv" qui sont en base64. 
Ainsi, c'est un tableau de 16 caractères qui est retourné. 
En python, si je me contente de faire un "base64.b64decode()", j'obtiens bien un chaîne de longueur 16, mais je ne sais pas si c'est ça qui est réellement attendu (il y a peut être une raison pour laquelle le javascript retourne un tableau de 16 et pas un chaine de 16). 


```
# r.content contient le contenu de ce qui est téléchargé à l'URL "https://www.izneo.com/book/{book_id}/{page}?type=full"
            aes = AES.new(base64.b64decode(key), AES.MODE_CBC, base64.b64decode(iv))
            uncrypted = aes.decrypt(r.content)
            file = open(store_path, "wb").write(uncrypted)
```

**Comment by izneo-get** [comment]
Bonne nouvelle !

J'ai modifié "izneo_get.py" pour qu'il puisse télécharger et déchiffrer les images. 
C'est disponible dans ce commit : 4e4e588a3409802093f8ebef33b76eda2af25038

Merci @mrdotb pour ton aide. 
Auparavant, en regardant le code JS j'avais déjà trouvé qu'il y avait un "key" et un "iv" et qu'il fallait déchiffrer l'image avec un algo "AES-CBC" mais je n'avais aucune idée de comment faire.

**Comment by mrdotb** [comment]
:clap:

**Comment by izneo-get** [comment]
@mrdotb si tu as accès à Cafeyn, je veux bien un coup de main pour le reverse engineering du code JS. 
On a chaque page qui est transmise en tant que PDF (codé en base64) de manière chiffrée par AES-CBC, mais je n'arrive pas à trouver ce qu'il attend comme "key" et comme "iv". 

La liste de toutes les URLs de PDF est dans le fichier json retourné par :
```
https://api.lekiosk.com/api/v1/reader/publications/1980894/issues/21648021/signedurls?timestamp=1601979863077
```

**Comment by mrdotb** [comment]
Envoie moi un mail sur mrdotb@protonmail.com avec un truc de tchat discord facebook. J'ai pas de compte sur ce site
