### ISSUE TITLE
BD achetées et dans la bibliothèque du compte

### ISSUE THREAD

**Issue by Lionjin** [izneo-get/izneo-get#16]
Bonjour,
Merci pour ce projet très utile.
Est-il possible de récupérer les pages d'une BD achetée et hors du catalogue abonnement, car je n'obtient que les 10 premières pages, soit ce genre de résultat.

https://www.izneo.com/fr/comics/thrillers-polars/black-hole-31491/black-hole-integrale-74697

<img width="880" alt="Capture d’écran 2021-01-24 à 21 59 15" src="https://user-images.githubusercontent.com/60135909/105643487-6bb11100-5e90-11eb-9d14-c49c3c7d1861.png">

Merci

**Comment by izneo-get** [comment]
Il faudrait que j'achète une BD hors abonnement afin de pouvoir développer cette partie.

**Comment by Lionjin** [comment]
On peut "acheter" des titres temporairement gratuits qui après l'achat à 0€ par le panier, vont directement dans la bibliothèque. Par exemple :
https://www.izneo.com/fr/bd/humour/achille-talon-les-impetueuses-tribulations-d-4852/le-langage-des-jeunes-explique-aux-moins-jeunes-9212
Je ne sais pas si ça fonctionne exactement comme un véritable achat mais ça y ressemble beaucoup.

**Comment by lowtekluldo** [comment]
J'allais faire la même remarque. Peut-être qu'avec le confinement qui se profile, les éditeurs vont redonner de vrais tomes gratuits comme lors du 1er confinement pendant lequel j'ai pu ajouter pas mal de BD à ma bibliothèque Izneo sans débourser un euro.
En tout cas, avant le changement de DRM, ça fonctionnait très bien pour télécharger des BD dans la bibliothèque car il y a des BD que j'ai achetées sur Izneo dans le but de les "dé-DRM-iser" grâce à Izneo-get et ça a très bien fonctionné.

**Comment by PhunkyBob** [comment]
Je viens de voir que j'avais déjà une BD "achetée" sur mon compte. 
J'arrive sans problème à la télécharger avec la dernière version du script. 

![image](https://user-images.githubusercontent.com/13345603/105725206-f5acb880-5f28-11eb-9173-c4e042bf4559.png)



@Lionjin pouvez-vous vérifier que vos variables de session et de cookies sont bien à jour dans votre fichier de conf ?

@lowtekluldo pourriez-vous tester de re-télécharger un livre que vous aviez "acheté" et qui n'est pas disponible dans l'abonnement et nous dire si vous êtes limité à 10 pages ?

**Comment by izneo-get** [comment]
Je viens de voir que j'avais déjà une BD "achetée" sur mon compte.
J'arrive sans problème à la télécharger avec la dernière version du script.

![image](https://user-images.githubusercontent.com/54946770/105725391-31478280-5f29-11eb-9d90-8ef211780950.png)


@Lionjin pouvez-vous vérifier que vos variables de session et de cookies sont bien à jour dans votre fichier de conf ?

@lowtekluldo pourriez-vous tester de re-télécharger un livre que vous aviez "acheté" et qui n'est pas disponible dans l'abonnement et nous dire si vous êtes limité à 10 pages ?

**Comment by Lionjin** [comment]
J'ai vérifié à chaque essai que les variables étaient bien à jour (au passage j'ai remarqué que la variable c03aab1711dbd2a02ea11200dde3e3d1 pouvait changer dans une même session...)

Ce que j'ai pu constater c'est que les titres achetés et présents dans le catalogue "abonnés" peuvent être récupérés sans problème (même si un message du script indique "cette BD n'est pas disponible dans l'abonnement")

<img width="662" alt="Capture d’écran 2021-01-25 à 17 59 41" src="https://user-images.githubusercontent.com/60135909/105747498-226cca00-5f41-11eb-8ec0-c08a65382825.png">
<img width="590" alt="Capture d’écran 2021-01-25 à 17 55 08" src="https://user-images.githubusercontent.com/60135909/105747587-3f090200-5f41-11eb-8ca6-9456524e2ea3.png">

par contre, les titres achetés et ne figurant pas dans le catalogue "abonnés" ne sont pas récupérés comme ci-dessous, avec le même message d'erreur

<img width="708" alt="Capture d’écran 2021-01-25 à 17 46 40" src="https://user-images.githubusercontent.com/60135909/105747709-6bbd1980-5f41-11eb-894f-307e298ce20b.png">
<img width="666" alt="Capture d’écran 2021-01-25 à 17 55 56" src="https://user-images.githubusercontent.com/60135909/105747745-7677ae80-5f41-11eb-8558-e7db53d4c162.png">

Je suis aussi tombé sur un titre récent qui est dans l'abonnement mais ne passe pas non plus, avec la même erreur
<img width="788" alt="Capture d’écran 2021-01-25 à 18 55 57" src="https://user-images.githubusercontent.com/60135909/105748083-ebe37f00-5f41-11eb-8dac-0904df876b96.png">
<img width="736" alt="Capture d’écran 2021-01-25 à 19 18 07" src="https://user-images.githubusercontent.com/60135909/105748218-1cc3b400-5f42-11eb-80a4-362e8876b3a4.png">

**Comment by izneo-get** [comment]
@Lionjin pouvez-vous vérifier que vous avez bien la dernière version ? 

Parce que chez moi : 
```
python izneo_get.py https://www.izneo.com/fr/roman-graphique/documentaire/dans-la-combi-de-thomas-pesquet-10338/dans-la-combi-de-thomas-pesquet-25432
``` 
n'a pas de problème pour télécharger la BD.

Dans votre erreur, cela parle de la ligne 411 et de 
```
if len(subtitle) > 0 and len(tome) > 0
``` 
Or cette portion de code était à cet endroit dans 4e4e588a3409802093f8ebef33b76eda2af25038 (5 octobre 2020).
Dans la version c6a072e65fa8ec3d0d5e93eb5ec192c21137c1e6 du 8 novembre 2020 ce n'est plus là, mais en ligne 415. 
(d'ailleurs, la correction de cette release est justement "Correction quand le tome n'est pas renseigne." ;) )

**Comment by Lionjin** [comment]
Bonsoir,
J'ai tout réinstallé et mis à jour le fichier de configuration.
La commande ramène bien cette fois l'exemple de BD complète et ça fonctionne bien avec toutes les titres inclus dans le catalogue "abonnés" que j'ai essayés.

> python izneo_get.py https://www.izneo.com/fr/roman-graphique/documentaire/dans-la-combi-de-thomas-pesquet-10338/dans-la-combi-de-thomas-pesquet-25432

Pour les BD achetées, après un premier essai infructueux, j'ai effacé tous les cookies et je me suis déconnecté en mettant à jour le fichier cfg et cette fois les BD achetées et non disponibles dans l'abonnement ont été téléchargées toutes les deux.
Donc si tout est proprement fait, ça marche aussi.

Merci encore

**Comment by lowtekluldo** [comment]
J'arrive un peu tard mais je viens de tout mettre à jour et lancer le téléchargement d'un manga acheté et c'est passé sans problème également.
![image](https://user-images.githubusercontent.com/59918084/105771781-68398a80-5f61-11eb-9748-531f43a0f67c.png)
