### ISSUE TITLE
Problème installation package prérequis

### ISSUE THREAD

**Issue by trimixst** [izneo-get/izneo-get#17]
Salut ! Tout d'abord merci pour ton travail, ça a l'air super !

Malheureusement je suis bloqué avec un histoire de package. Impossible de trouver le module "Crypto". J'ai python 3.9 avec tous les packages prérequis installés (y compris pycryptodome), pourtant il m'affiche encore le message suivant lorsque je lance python izneo_get.py : 
`from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'`

J'ai déjà épluché à peu près tous les threads sur le sujet sur google. Après j'ai jamais fait de programmation en python et j'ai des connaissances assez limitées en ligne de commande.

Est-ce que tu aurais une idée ?

**Comment by izneo-get** [comment]
Pouvez-vous me dire sur quel environnement vous êtes ?

**Comment by izneo-get** [comment]
Sous Windows, j'ai essayé de refaire un nouvel environnement en faisant l'installation des dépendances à la main : 

Création du répertoire de travail : 
```
cd c:\Temp
git clone https://github.com/izneo-get/izneo-get.git
cd izneo-get
```

Création d'un environnement virtuel : 
```
python -m venv env
env\Scripts\activate
```

Installation des dépendances : 
```
python.exe -m pip install --upgrade pip
python.exe -m pip install pycryptodome
python.exe -m pip install requests
python.exe -m pip install beautifulsoup4
python.exe -m pip install Pillow
```

Création d'un fichier de configuration : 
```
cp izneo_get.cfg.sample izneo_get.cfg
```

Edition du fichier `izneo_get.cfg` avec les bonnes valeurs de `session_id` et `cfduid`.

Exécution du script : 
```
python izneo_get.py https://www.izneo.com/fr/bd/heroic-fantasy/once-and-future-34875/once-and-future-chapitre-1-84575
```
Et tout fonctionne.

**Comment by trimixst** [comment]
merci pour ton aide. Oui j'ai complètement oublié de mentionner que je suis sous Windows 10. J'essaie de m'y remettre tout à l'heure et te redis.

**Comment by Baladash** [comment]
Bonjour,

Les attributs suivants doivent manquer dans ta ligne de commande :

  --session-id SESSION_ID, -s SESSION_ID
                        L'identifiant de session
  --cfduid CFDUID, -c CFDUID
                        L'identifiant cfduid

Cdt.

**Comment by izneo-get** [comment]
Il n'y a donc plus de problème de dépendances, c'est un bon point.

Le fait d'être bloqué à 10 pages arrive lorsque les identifiants de session ne sont pas bons. 
A mon avis, le fait de s'être déconnecté du site Izneo invalide justement ces identifiants de session. 

Il faut : 
- se connecter à Izneo
- regarder les valeurs dans les cookies
- les utiliser dans le script (soit en ligne de commande, soit dans le fichier de configuration)

**Comment by izneo-get** [comment]
Problème de dépendances résolu.

**Comment by trimixst** [comment]
> Il n'y a donc plus de problème de dépendances, c'est un bon point.
> 
> Le fait d'être bloqué à 10 pages arrive lorsque les identifiants de session ne sont pas bons.
> A mon avis, le fait de s'être déconnecté du site Izneo invalide justement ces identifiants de session.
> 
> Il faut :
> 
> * se connecter à Izneo sur son navigateur
> * regarder les valeurs dans les cookies
> * les utiliser dans le script (soit en ligne de commande, soit dans le fichier de configuration)

Salut,
Désolé pour ma réponse tardive. Effectivement je crois que ça venait des cookies. Merci encore !
