### ISSUE TITLE
Problème sur une webtoon

### ISSUE THREAD

**Issue by Mahora2106** [izneo-get/izneo-get#18]
Bonjour,
J'ai rencontré un souci sur une webtoon et apparemment pour le moment juste celle-ci. Alors je ne sais pas d'où vraiment cela provient et si on peut faire quelque chose. Je vous mets un screen du message que cela me met.
![Sans titre-1](https://user-images.githubusercontent.com/71670560/107054674-ba37a700-67d0-11eb-9bfb-6fad1e3a0f63.jpg)

**Comment by izneo-get** [comment]
Ca sent le "?" que Windows n'aime pas dans les noms de fichiers. 

Je viens de faire un patch dans a045f6057da9ad67348e58b83db224d47d66df54

Je vous invite à utiliser plutôt le script `izneo_get.py` qui ne se base pas sur Selenium et qui est bien plus rapide.

**Comment by Mahora2106** [comment]
oki je teste et je vous redis ça
Merci

**Comment by Mahora2106** [comment]
C'est bon cela fonctionne super merci beaucoup^^
