### ISSUE TITLE
Problème de numérotation

### ISSUE THREAD

**Issue by Mahora2106** [izneo-get/izneo-get#19]
Bonjour, 
alors lors de mon dernier message il y avait un souci avec les noms des fichiers apparemment, ce que vous avez corrigé, mais du coup cela rajoute des numéros avant Episode 1 par exemple ou Tome 1, et lorsque qu'il y a 3 chriffres par exemple Episode 101 il y a que les deux derniers qui se mettent devant par exemple 01 - Episode 101 du coup je me retrouve avec deux 01 et il se mette l'un après l'autre et nom par ordre d'épisode. Je vous laisse un petit screen ça sera plus parlant. Du coup si c'est possible de faire qqc.

![Capture](https://user-images.githubusercontent.com/71670560/109489631-7199a380-7a87-11eb-9ecc-42a708787dc6.PNG)

**Comment by izneo-get** [comment]
Je viens de corriger le script `izneo_get.py` : bbfd641

Par contre il faudra attendre un peu pour avoir un binaire Windows.

**Comment by izneo-get** [comment]
Le binaire est disponible : https://github.com/izneo-get/izneo-get/releases/latest
