### ISSUE TITLE
'error on line 421'

### ISSUE THREAD

**Issue by ehanuise** [izneo-get/izneo-get#2]
I get an error message :
python izneo_get.py https://www.izneo.com/fr/roman-graphique/documentaire/dans-la-combi-de-thomas-pesquet-10338/dans-la-combi-de-thomas-pesquet-25432 --config ./izneo_get.cfg
  File "izneo_get.py", line 421
    print(progress_message, end="")
                               ^

(linux, python 3.8, all prerequisites installed, cfid and session ID in the config file izneo_get.cfg)

**Comment by izneo-get** [comment]
Are you 100% sure you are in a Python 3.8 environment?

Because this looks like your Python doesn't recognize "print" as a function, like in the 2.x version of Python.

**Comment by ehanuise** [comment]
Oh indeed.
Had python 2.7, installed 3.8 as per requirements and didn't realize 2.7 was still default on the system :/
solved now, thanks!

(debian/ubuntu users : to solve the issue with several versions of python, use update-alternatives to map each version and priority, the choose the system default.)
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1
sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 10
sudo update-alternatives --config python
