### ISSUE TITLE
Comment link mon compte izneo ?

### ISSUE THREAD

**Issue by Hyakka52** [izneo-get/izneo-get#20]
Bonjour, j'ai essayé de trouver la solution par moi-même en lisant et relisant les instructions, mais je suis un noob total dans tout ce qui touche à python et je n'arrive pas à télécharger un tome complet. Quand j'entre l'URL bien que je sois connecté à mon compte izneo il ne me télécharge que les 10 premières pages (la preview ?) alors que j'ai bien acheté le tome complet et qu'il fonctionne sur le site

Edit : je suis sur windows 10

**Comment by izneo-get** [comment]
Avez vous bien mis à jour le fichier de configuration pour lui donner les bonnes valeurs pour `cfduid`et `session_id` ?


Dans la [documentation](https://github.com/izneo-get/izneo-get#izneo_get--izneo_get_selenium) : 
CFDUID est la valeur de "cfduid" dans le cookie.
SESSION_ID est la valeur de "c03aab1711dbd2a02ea11200dde3e3d1" dans le cookie.

Pour les obtenir, identifiez vous sur https://www.izneo.com/fr/ et recherchez votre cookie avec votre navigateur web.
Chrome

Menu --> Plus d'outils --> Outils de développements
Application / Storage / Cookies
et recherchez le cookie "https://www.izneo.com".
Firefox

Menu --> Developpement web --> Inspecteur de stockage --> Cookies
et recherchez le cookie "https://www.izneo.com".

**Comment by Hyakka52** [comment]
Alors j'ai réussi à le faire fonctionner, j'utilisais "izneo_get_selenium.py" au lieu de "python izneo_get.py", comme dit j'y connais vraiment rien. En tous cas merci, la qualité des images est au top, vous faites du très bon travail ^^
