### ISSUE TITLE
izneo_list.py only returns the first 40 results

### ISSUE THREAD

**Issue by foux** [izneo-get/izneo-get#21]
Hi there!

First thanks for the wonderfull script!
I've got an issue with `izneo_list.py` with volumes with more than 40 issues.

For example `python izneo_list.py --full-only https://www.izneo.com/fr/bd/humour/spirou-et-fantasio-964` will only returns the first 40 issues of 55.

Is there any way to cricumvine that?

Thanks!

**Comment by izneo-get** [comment]
It's weird. 
The API returns only 40 results. 
I have to find how I can get all the results.

**Comment by foux** [comment]
Perhaps a pagination?

**Comment by izneo-get** [comment]
No pagination available on this API.

I changed the method to gather volumes. I now use another API (with pagination). It needs more calls, but it works. 

Please pull (6b1a561) and tell me if it's OK for you.

**Comment by foux** [comment]
The issue order is inversed, but not an issue, works great for me, thanks for the quick fix!
