### ISSUE TITLE
Impossible de se connecter avec le driver

### ISSUE THREAD

**Issue by AlexanderVanUffelen** [izneo-get/izneo-get#24]
The "izneo_get.py" works great.
However, the trying to use the "izneo_get_selenium.py" script, I get:
`Impossible de se connecter avec le driver "./chromedriver85.exe"`    
`Impossible de se connecter avec le driver "./bin/chromedriver85.exe"`
`Impossible de se connecter avec le driver "./bin/chromedriver89.exe"`
`Impossible de se connecter avec le driver "./bin/chromedriver88.exe"`
`Impossible de se connecter avec le driver "./bin/chromedriver86.exe"`
`Impossible de se connecter avec le driver "./bin/chromedriver84.exe"`
`Traceback (most recent call last):`
`  File "izneo_get_selenium.py", line 378, in <module>`
`    driver.set_window_size(dimension, dimension)`
`NameError: name 'driver' is not defined`

Using Ubuntu 20.04

EDIT: Tried it on windows, and it worked. Seems to be a linux problem?

**Comment by izneo-get** [comment]
Since you are on Linux, you have to use other [Chrome drivers](https://chromedriver.chromium.org/downloads). 
Then you yave to change the `prefered_driver` parameter in the config file to give the path of your Chrome driver. 


Since `izneo-get.py` works fine, I strongly advise to use it instead of selenium version because it gets source images whereas Selenium version gets screenshots of images.

**Comment by AlexanderVanUffelen** [comment]
Downloaded the Linux drivers and still had the error message. So I made the error more verbose (instead of 'Impossible de se connecter avec le driver'):

`Message: unknown error: cannot find Chrome binary`

Apparently Chrome needs to be installed on the system.
So I installed Chrome, and now selenium version works.

Why was the selenium version implemented if it does not get source images?

**Comment by izneo-get** [comment]
> Apparently Chrome needs to be installed on the system.

Yes. ChromeDriver is only a driver to handle Chrome. 


> Why was the selenium version implemented if it does not get source images?

At first, images where not crypted in Izneo and I made `izneo-get` to grab them.
After few years, they decided to crypt their images and the script was useless. So I made `izneo-get-selenium` to retreive images using a browser. 
In parallel I worked on a way to crack the encryption. It took months and I finally made a new version of `izneo-get`.

**Comment by AlexanderVanUffelen** [comment]
> Yes. ChromeDriver is only a driver to handle Chrome.

Maybe this could be added under 'Prérequis'?

> It took months and I finally made a new version

Thank you, I appreciate the work!

**Comment by izneo-get** [comment]
> Maybe this could be added under 'Prérequis'?

It's done.

And I also added 

> Si `izneo-get` fonctionne, il est préférable de l'utiliser (plus rapide et pas de transformation faite sur les images sources). `izneo_get_selenium` est une version qui a été développée avant que le déchiffrement des images soit possible.

in the begining of the documentation.
