### ISSUE TITLE
Absence du cookie CFDUID

### ISSUE THREAD

**Issue by sholine** [izneo-get/izneo-get#26]
Bonjour,
Je constate aujourd'hui que le cookie CFDUID n'est plus envoyé par Izneo. En ligne de commande, j'ai tout de même renseigné le paramètre "-c" avec une chaine bidon et ça semble marcher.
Mis à part par contre que le téléchargement des images est beaucoup plus lent (téléchargement d'un groupe d'images à un rythme normal (entre 10 et 30 environ) puis tout à cause pause qui peut aller jusqu'à 1 min, 1min 30 et ça reprend (timeout d'une requête ?) et ça reprend...

(à noter que je ne vois pas comment le programme accès à mes BD achetées sans ce paramètre du coup...)
Si je peux aider d'une quelconque manière.

**Comment by izneo-get** [comment]
Bonjour,
Il fil du temps, Izneo a changé le nom de ses cookies.
Initialement, il y avait `session_id` et `cfduid` et j'ai utilisé ces noms dans le fichier de configuration. 
Puis `session_id` a été renommé en `c03aab1711dbd2a02ea11200dde3e3d1` chez Izneo. J'ai décidé de conserver le nom initial dans le fichier de configuration. 

Désormais c'est `cfduid` qui a été renommé en `PHPSESSID`. 
Cf e0e0432

Je n'ai toujours pas changé le nom des variables dans la config, pour des raison de rétro-compatibilité (même si je suis conscient que `session_id` et `PHPSESSIONID` ont des noms très proches alors qu'il sont 2 choses différentes).

**Comment by sholine** [comment]
Top, merci pour la précision ! Et merci pour le travail sur cet outil que je trouve très bien fait.

**Comment by izneo-get** [comment]
C'était mon premier script. Il mériterait d'être réécrit bien plus propre, mais je n'ai pas le courage de passer du temps sur quelque chose qui fonctionne 😆
