### ISSUE TITLE
Delitoon

### ISSUE THREAD

**Issue by Mahora2106** [izneo-get/izneo-get#28]
Bonjour, 
Je ne savais pas trop où demander du coup je fais ça ici. Tout d'abord merci beaucoup pour le script d'Izneo. 
Je voulais demander si jamais c'était possible de faire la même chose avec Delitoon ? Certaines webtoons ne sont pas dans l'application à cause de leur maturité par exemple donc ça serait tellement plus simple de tout avoir sur son tel.

**Comment by izneo-get** [comment]
Bonjour,
Le problème de Delitoon (et d'autres sites du même genre), c'est que les pages ne sont pas distinctes. 
C'est l'équivalent d'une seule grande page, mais découpée à des hauteurs fixes. 
Même en faisant un outil qui permettrait de récupérer cette grande page il ne serait pas pratique de la lire.

**Comment by Mahora2106** [comment]
pourtant on peut récupérer les images sur delitoon. les images coupées, c'est surtout que c'est long de faire chapitre par chapitre. Par exemple avec firefox et une extension du genre download all image ça fonctionne, mais c'est surtout long. C'est pour ça qu'un petit script comme celui d'izneo c'est pratique. C'est d'ailleurs comme sur Izneo enfin les images coupés, après la mise en place est peut-être différente effectivement

**Comment by izneo-get** [comment]
Voici à quoi correspondent les 5 premières "pages" d'une BD de ce site : 

![5 pages](https://i.imgur.com/M6S6wn6.png)
J'ai mis un bord rouge pour bien montrer le découpage. 

On constate qu'il ne respecte pas le découpage des cases : on peut se retrouver avec une partie d'une case dans une image et une autre partie dans l'image suivante.

**Comment by Mahora2106** [comment]
Oui ça c'est normal, c'est pareil sur Izneo, mais il existe des applications pour lire sur tel où cela met tout bout à bout automatiquement on lit en vertical donc pas de souci. Il existe aussi des logiciels pour recoller les bouts si on le souhaite vraiment, mais l'application de lecture suffit

**Comment by Mahora2106** [comment]
Bonjour,
Du coup est-ce possible ? Même avec les images découpés comme vous avez montré ce n'est pas un problème. 
Merci par avance

**Comment by izneo-get** [comment]
Bonjour, 
Oui, c'est possible. 

Par contre cela nécessite un peu de temps à développer (que je n'ai actuellement pas). 
Il faut que je réfléchisse pour savoir si c'est une évolution du script `izneo-get` ou si c'est un nouveau script à créer from scratch.

**Comment by Mahora2106** [comment]
D'accord pas de soucis.
Merci beaucoup. Oui j'imagine que cela prend du temps.
Courage 💪
