### ISSUE TITLE
Souci avec le script

### ISSUE THREAD

**Issue by Mahora2106** [izneo-get/izneo-get#29]
Bonjour, 
Je ne sais pas si je suis la seule, mais je n'arrive plus à utiliser le script, ça me met une erreur. Je sais pas si j'ai fais une mouvaise manip où si cela vient du scrpit, voilà ce que j'ai : 
![erreur script](https://user-images.githubusercontent.com/71670560/127314673-d7bff2ee-fae3-4c32-96f3-da5e44e4d2bc.jpg)

**Comment by izneo-get** [comment]
Cette erreur arrive quand toutes les dépendances ne sont pas installées. 
En l’occurrence ici, il vous manque "requests".
```
python.exe -m pip install requests
```

Je vous conseille de faire un environnement dédié à `izneo-get` comme indiqué dans [la documentation](https://github.com/izneo-get/izneo-get#installation-1).

**Comment by Mahora2106** [comment]
Je sais pas trop ce qu'il s'est passé, mais python et pi n'était plus dans mon PATH du coup j'avais remis python, mais j'ai pas pensé qu'il fallait refaire le requirement merci beaucoup, ça l'air de remarcher

**Comment by izneo-get** [comment]
Parfait !
