### ISSUE TITLE
izneo_list.py no results, no error

### ISSUE THREAD

**Issue by ehanuise** [izneo-get/izneo-get#3]
I can use izneo_get.py on my system.
However izneo_list.py gives no results and exits without error.
I looked in the output folder, no list, nothing is output in the console, so where's the list ?

```
user@host:~/apps/izneo-get$ python izneo_list.py --series --config ./izneo_get.cfg https://www.izneo.com/fr/manga-et-simultrad/shonen/naruto-567
user@host:~/apps/izneo-get$ python izneo_list.py https://www.izneo.com/fr/manga-et-simultrad/shonen/naruto-567
user@host:~/apps/izneo-get$ python izneo_list.py https://www.izneo.com/fr/manga-et-simultrad/shonen/naruto-567 --full-only --force-title
user@host:~/apps/izneo-get$ python izneo_list.py "largo"

```

**Comment by izneo-get** [comment]
Indeed, Izneo changed it's way of displaying results.

**Comment by ehanuise** [comment]
Thanks for the quick reply :)
OK, browser extensions like linkgopher will do.
I expect they change the layout on a regular basis.

**Comment by izneo-get** [comment]
I've made a correction to be able to retrieve the list from the serie URL.

```
python izneo_list.py https://www.izneo.com/fr/manga-et-simultrad/shonen/naruto-567
```
and
```
python izneo_list.py --full-only https://www.izneo.com/fr/manga-et-simultrad/shonen/naruto-567
```
should now work.



ps : no need to add "--config ./izneo_get.cfg" when you config file is "./izneo_get.cfg".

**Comment by izneo-get** [comment]
I've made an update to correct cases when there is a lot of volumes in the same serie.

**Comment by ehanuise** [comment]
Great! thanks :)
