### ISSUE TITLE
Impossible de télécharger un  album complet

### ISSUE THREAD

**Issue by ValouSSB** [izneo-get/izneo-get#31]
Bonjour, j'essaie de télécharger un album que j'ai acheté sur mon compte, mais le script ne me télécharge que les pages gratuites dispo sur le site. J'ai bien essayé avec la version selenium, ou en changeant les ids des cookies, ou de navigateur ( chrome, brave et firefox) mais rien ne fait il ne télécharge que 10 pages. J'ai essayé avec un album gratuit mais ça ne marche pas non plus. Si jamais il y a une erreur dans ce que j'ai fais j'aimerai bien savoir. Cordialement
![izneo](https://user-images.githubusercontent.com/90838038/133640319-44a8458b-0af5-4391-a55f-7b79d89c63a9.png)

**Comment by izneo-get** [comment]
Pouvez-vous me confirmer que : 
- Vous utilisez bien la dernière version de `izneo_get.py` 8001f68 ? 
- Dans le fichier de config, vous avez bien mis dans `session_id` la valeur du cookie `c03aab1711dbd2a02ea11200dde3e3d1` ?
- Dans le fichier de config, vous avez bien mis dans `cfduid` la valeur du cookie `PHPSESSID` ?
(et non pas l'inverse)

Je viens de tester à l'instant, ça télécharge mon album complet.

**Comment by ValouSSB** [comment]
Je ne sais oas comment vérifier la version de izneo_get.py mais je l'ai retéléchargé avant d'envoyer mon message avec la méthode indiquée, quant à mon fichier config le voilà : 
![image](https://user-images.githubusercontent.com/90838038/133673687-37356da1-1f21-46f2-a029-f78f704c2a99.png)

**Comment by izneo-get** [comment]
Vous avez inversé les 2 valeurs. 
Si je tape 
![cmd](https://i.imgur.com/jJR6QfF.png)
ça fonctionne.

**Comment by ValouSSB** [comment]
Quelles valeurs ? j'ai essayé d'échanger les deux id avec la même syntaxe sans succès
![image](https://user-images.githubusercontent.com/90838038/133679030-df48ee1d-ef02-47b3-a02a-1d6ae9f224d7.png)

**Comment by izneo-get** [comment]
Pouvez-vous faire un screenshot de vos cookies ?
Pouvez-vous essayer sans les guillemets autour des valeurs (comme dans mon screenshot) ?
Pouvez-vous faire un `git pull` pour être certain d'avoir la dernière version de `izneo-get.py` ? 

Ce qui est très étrange c'est qu'en prenant les valeurs que vous avez données dans le screenshot de Notepad, j'ai réussi à récupérer votre BD entièrement...

**Comment by ValouSSB** [comment]
![image](https://user-images.githubusercontent.com/90838038/133682305-6a8547b7-4368-47dd-9404-6e16f751eb56.png)

**Comment by izneo-get** [comment]
>     * Dans le fichier de config, vous avez bien mis dans `session_id` la valeur du cookie `c03aab1711dbd2a02ea11200dde3e3d1` ?
> 
>     * Dans le fichier de config, vous avez bien mis dans `cfduid` la valeur du cookie `PHPSESSID` ?
>       (et non pas l'inverse)

Dans votre dernier screenshot, vous faites l'inverse. 

![capture](https://i.imgur.com/S3hWKV8.png)

**Comment by ValouSSB** [comment]
Enfin ça marche ! J'ai pourtant fait dans les deux sens sur chrome et firefox mais pas sur brave et là ça marche... Merci beaucoup en tout cas

**Comment by izneo-get** [comment]
Je pense que le fait d'ouvrir une session sur un autre navigateur a rendu l'autre token invalide.
