### ISSUE TITLE
PHPSESSID n'est plus disponible

### ISSUE THREAD

**Issue by Lightjohn** [izneo-get/izneo-get#32]
Bonjour,

En voulant utiliser ce script, je ne peux trouver le PHPSESSID dans le cookie.
A priori ce n'est désormais plus nécessaire: j'ai commenté dans le code et ça marche très bien juste avec le `session_id`

![image](https://user-images.githubusercontent.com/7568409/134151222-dc384a7b-3c7c-4607-8ec2-dfa577b49336.png)

**Comment by izneo-get** [comment]
C'est ce qui est dit dans le `README.md` : 
> CFDUID est la valeur de "PHPSESSID" dans les cookies. Cette information semble désormais facultative.

Je mettrai à jour à la prochaine release.
