### ISSUE TITLE
File not found / line 509

### ISSUE THREAD

**Issue by notna1109** [izneo-get/izneo-get#33]
Hello 

j'ai une petite erreur dans le script: ce n'est pas en line 509 mais en line 513

E:\Programmes\Python\izneo-get-master>python izneo_get.py https://www.izneo.com/fr/abo/bd/fantastique/la-boite-a-musique-10295/la-boite-a-musique-tome-4-la-mysterieuse-disparition-82436 -f cbz --force-title "Boite à Musique (La) - 05 - Tome "
URL: https://www.izneo.com/fr/abo/bd/fantastique/la-boite-a-musique-10295/la-boite-a-musique-tome-4-la-mysterieuse-disparition-82436
Téléchargement de "La boîte à musique - 04. La boîte à musique - Tome 4 - La mystérieuse disparition" en tant que "Boite à Musique (La) - 05 - Tome "
57 pages attendues
Destination : E:\Programmes\Python\izneo-get-master/DOWNLOADS/Boite à Musique (La) - 05 - Tome
Traceback (most recent call last):
  File "izneo_get.py", line 513, in <module>
    file = open(store_path, "wb").write(uncrypted)
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Programmes\\Python\\izneo-get-master/DOWNLOADS/Boite à Musique (La) - 05 - Tome /Boite à Musique (La) - 05 - Tome  001.jpg'

Il y aurait il un moyen d'y remédier? Merci

**Comment by izneo-get** [comment]
Bonjour,

Pouvez-vous vérifier que vous avez bien la dernière version du script ?
``` 
git pull
```

En effet, la ligne 513 ne correspond pas au code qui est annoncé poser problème. 
J'ai l'impression que vous êtes sur une ancienne version.

De mon côté, si j'exécute la commande
```
python izneo_get.py https://www.izneo.com/fr/abo/bd/fantastique/la-boite-a-musique-10295/la-boite-a-musique-tome-4-la-mysterieuse-disparition-82436 -f cbz --force-title "Boite à Musique (La) - 04"
```
j'obtiens 
```
Version 0.09.02 (version officielle)

URL: https://www.izneo.com/fr/abo/bd/fantastique/la-boite-a-musique-10295/la-boite-a-musique-tome-4-la-mysterieuse-disparition-82436
Cette BD n'est pas disponible dans l'abonnement
Téléchargement de "La boîte à musique - 04. La boîte à musique - Tome 4 - La mystérieuse disparition" en tant que "Boite à Musique (La) - 04"
10 pages attendues
Destination : C:\Python\izneo-get/DOWNLOADS/Boite à Musique (La) - 04
[page 10 / ~10] .......... OK
Création du CBZ
Terminé !
```

**Comment by izneo-get** [comment]
Re,

Je constate que la commande n'est pas la même dans votre post que dans l'email sur lequel je m'étais basé. 

Le problème vient du fait que vous avez mis un espace à la fin du titre :
```
--force-title "Boite à Musique (La) - 05 - Tome "
```

Or quand on crée un répertoire Windows avec un espace à la fin, celui-ci n'est pas pris en compte. 

Je viens de pousser une correction qui supprimera automatiquement les espaces de fin de nom de fichier / répertoire.

**Comment by notna1109** [comment]
Bonjour en effet c'est bon a savoir. Tout fonctionne. Merci.
