### ISSUE TITLE
Ajouter mangas.io

### ISSUE THREAD

**Issue by Ever4engel** [izneo-get/izneo-get#36]
possibilité d'ajouter mangas.io ?

**Comment by izneo-get** [comment]
Bonjour, 
Ce n'est pas prévu pour le moment. Cela impliquerait une grosse refonte du code. 
Néanmoins, je garde l'idée sous le coude.

**Comment by izneo-get** [comment]
Est-ce que vous utilisez Python ou directement l'exécutable ?
Si vous utilisez directement le script, je publierai sur une branche spécifique mes avancées sur la partie "Mangas.io". 
Pour l'instant, mes tests sont plutôt positifs. Mais n'ayant pas de compte payant, je ne sais pas si cela fonctionnera pareil sur les BD disponibles uniquement pour les comptes payants. 

De plus, je ne sais pas s'ils ont des alertes de sécurité qui pourraient identifier les comptes qui téléchargent tout leur catalogue. 
C'était le cas pour un autre site de publication de magazine qui a bloqué les comptes de certains utilisateurs et qui a fait fermer le repo git de l'outil. 

D'ailleurs je me demande s'il ne serait pas plus sage de séparer les 2 outils, justement au cas où un des éditeurs demande la fermeture de l'outil 🤔

**Comment by Ever4engel** [comment]
> Est-ce que vous utilisez Python ou directement l'exécutable ? Si vous utilisez directement le script, je publierai sur une branche spécifique mes avancées sur la partie "Mangas.io". Pour l'instant, mes tests sont plutôt positifs. Mais n'ayant pas de compte payant, je ne sais pas si cela fonctionnera pareil sur les BD disponibles uniquement pour les comptes payants.
> 
> De plus, je ne sais pas s'ils ont des alertes de sécurité qui pourraient identifier les comptes qui téléchargent tout leur catalogue. C'était le cas pour un autre site de publication de magazines qui a bloqué les comptes de certains utilisateurs et qui a fait fermer le repo git de l'outil.
> 
> D'ailleurs je me demande s'il ne serait pas plus sage de séparer les 2 outils, justement au cas où un des éditeurs demande la fermeture de l'outil 🤔

J'utilise ton script python.

pour ça j'avais demandé que ce soit sous le repo `mangas.io-get` comme ça aucune crainte de fermeture abusive de izneo avec. pour l'alerte je sais pas pour être franc mais d'après ce que j'ai vu coté console et requêtes réseaux y pas de fichiers json/js louches.

**Comment by izneo-get** [comment]
> pour l'alerte je sais pas pour être franc mais d'après ce que j'ai vu coté console et requêtes réseaux y pas de fichiers json/js louches

Les alertes de l'éditeur qui a fait fermer mon autre repo étaient côté serveur. 
Du genre "_je constate que le compte a visualisé X pages en moins de Y secondes, donc ça doit être un bot_". 


Je vous tiens au courant dès que je mets une première version sur https://github.com/izneo-get/mangas-get 
Il faut encore que je gère toute la partie "paramétrage / ligne de commande".

**Comment by Ever4engel** [comment]
> > pour l'alerte je sais pas pour être franc mais d'après ce que j'ai vu coté console et requêtes réseaux y pas de fichiers json/js louches
> 
> Les alertes de l'éditeur qui a fait fermer mon autre repo étaient côté serveur. Du genre "_je constate que le compte a visualisé X pages en moins de Y secondes, donc ça doit être un bot_".
> 
> Je vous tiens au courant dès que je mets une première version sur https://github.com/izneo-get/mangas-get Il faut encore que je gère toute la partie "paramétrage / ligne de commande". C'est toujours la partie "emballage" qui prend le plus de temps 😅

ahah en tout cas merci ^^ 
je pouvais uri call les liens directs des images racine mais je connais que dalle au api (chaque image a un hash unique qui expire dès que le payload est effectué sur le lecteur du site). ça va faciliter le rip ça

je demande si c'est possible de mettre un délai raisonnable de de rip entre chaque images et la suivante genre 250/500 ms comme ça peu de chances qu'ils détectent ça

**Comment by izneo-get** [comment]
> je demande si c'est possible de mettre un délai raisonnable de de rip entre chaque images et la suivante genre 250/500 ms comme ça peu de chances qu'ils détectent ça

C'était ce qui avait été fait sur l'autre service. 
Même avec un délais de plusieurs secondes entre chaque page, les comptes ont été bloqués dans les heures qui ont suivies.

**Comment by Ever4engel** [comment]
> > je demande si c'est possible de mettre un délai raisonnable de de rip entre chaque images et la suivante genre 250/500 ms comme ça peu de chances qu'ils détectent ça
> 
> C'était ce qui avait été fait sur l'autre service. Même avec un délais de plusieurs secondes entre chaque page, les comptes ont été bloqués dans les heures qui ont suivies.

C'est chaud quand même.

**Comment by izneo-get** [comment]
Je vous laisse tester et me faire des retours : https://github.com/izneo-get/mangas-get

**Comment by Ever4engel** [comment]
> Je vous laisse tester et me faire des retours : https://github.com/izneo-get/mangas-get Les options sont légèrement différentes (par défaut ça fait un CBZ, par défaut ça conserve le format d'image original, ...) mais vous devriez vous y retrouver facilement.

merci je vais voir ça 
aller git clone :)
