### ISSUE TITLE
izneo_list ne fonctionne pas / izneo_list not working

### ISSUE THREAD

**Issue by tweety231323** [izneo-get/izneo-get#37]
izneo_list.py :
Traceback (dernier appel le plus récent) :
  Fichier "C:\Users\abc\Desktop\izneo_list.py", ligne 234, in <module>
    nouveaux_résultats += parse_html_json(r.text, force_title=force_title)
  Fichier "C:\Users\abc\Desltop\izneo_list.py", ligne 131, dans parse_html_json
    for vol in content['albums'][current_type] :
KeyError : "albums" (erreur de clé)

Les URLs sont-elles hors ligne ?
https://www.izneo.com/fr/search-album-list
https://www.izneo.com/fr/search-series-list

Traduit avec www.DeepL.com/Translator (version gratuite)
----------------------------------------------------------
izneo_list.py:
Traceback (most recent call last):
  File "C:\Users\abc\Desktop\izneo_list.py", line 234, in <module>
    new_results += parse_html_json(r.text, force_title=force_title)
  File "C:\Users\abc\Desltop\izneo_list.py", line 131, in parse_html_json
    for vol in content['albums'][current_type]:
KeyError: 'albums'

Are the URLs offline?
https://www.izneo.com/fr/search-album-list
https://www.izneo.com/fr/search-series-list

**Comment by izneo-get** [comment]
L'URL https://www.izneo.com/fr/search-album-list ne fonctionne plus.

J'ai modifié le script : 3795b46
Cf. https://github.com/izneo-get/izneo-get/issues/41
