### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by Baladash** [izneo-get/izneo-get#39]
Bonjour,

J'ai ce genre d'erreur sur des BD disponibles dans l'abonnement, et je n'ai eu aucun problème avec les autres tomes de ces mêmes BD :

URL: https://www.izneo.com/fr/bd/science-fiction/beast-179/amrath-la-reine-sauvage-413
Téléchargement de "Beast - 02. Amrath, la reine sauvage "
48 pages attendues
Destination : E:\abcd\/fr/bd/science-fiction/beast/Beast - 02. Amrath, la reine sauvage
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\Tools\scripts\izneo_get.py", line 531, in <module>
    file = open(store_path, "wb").write(uncrypted)
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\abcd\\/fr/bd/science-fiction/beast/Beast - 02. Amrath, la reine sauvage /Beast - 02. Amrath, la reine sauvage  001.jpg'

URL: https://www.izneo.com/fr/bd/humour/le-petit-spirou-presente-752/ma-prof-de-calcul-2537
Téléchargement de "Le Petit Spirou présente - 03. Ma prof de calcul "
32 pages attendues
Destination : E:\abcd\/fr/bd/humour/le-petit-spirou-presente/Le Petit Spirou présente - 03. Ma prof de calcul
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\Tools\scripts\izneo_get.py", line 531, in <module>
    file = open(store_path, "wb").write(uncrypted)
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\abcd\\/fr/bd/humour/le-petit-spirou-presente/Le Petit Spirou présente - 03. Ma prof de calcul /Le Petit Spirou présente - 03. Ma prof de calcul  001.jpg'

URL: https://www.izneo.com/fr/bd/humour/lucky-luke-dupuis-988/tortillas-pour-les-dalton-2209
Téléchargement de "Lucky Luke (Dupuis) - 31. Tortillas pour les Dalton "
47 pages attendues
Destination : E:\abcd\/fr/bd/humour/lucky-luke-dupuis/Lucky Luke (Dupuis) - 31. Tortillas pour les Dalton
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\Tools\scripts\izneo_get.py", line 531, in <module>
    file = open(store_path, "wb").write(uncrypted)
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\abcd\\/fr/bd/humour/lucky-luke-dupuis/Lucky Luke (Dupuis) - 31. Tortillas pour les Dalton /Lucky Luke (Dupuis) - 31. Tortillas pour les Dalton  001.jpg'

Cordialement.

**Comment by izneo-get** [comment]
Ça essaye de créer un répertoire 
E:\abcd\/fr/bd/

Pouvez-vous essayer de changer la configuration pour remplacer le répertoire de sortie

E:\abcd\

Par

E:\abcd

(Enlever le dernier "/")
?

**Comment by Baladash** [comment]
Même chose, mais encore une fois je n'ai eu aucun problème avec les autres tomes.

**Comment by izneo-get** [comment]
Je regarderai quand j'aurai accès à un vrai ordinateur.

**Comment by izneo-get** [comment]
Je n'arrive pas à reproduire le problème. 
Quelques questions : 
- Sur quel OS êtes-vous ? Peut-être que la virgule dans le nom du fichier pose problème sur votre OS. Essayez de forcer le nom avec l'option `--force-title` pour voir ?
- Etes-vous sûr d'utiliser la dernière version de l'outil (actuellement `0.09.03`) ? 
Vous avez un message d'erreur qui parle de la ligne 531 pour le code `file = open(store_path, "wb").write(uncrypted)`, mais chez moi cette ligne de code se trouve en ligne 547.

**Comment by izneo-get** [comment]
Pas de nouvelles. Ancienne version. Je ferme.
