### ISSUE TITLE
pages over 100 overwrite previous pages

### ISSUE THREAD

**Issue by ehanuise** [izneo-get/izneo-get#4]
example : https://www.izneo.com/fr/bd/documentaire/l-affaire-des-affaires-465
volumes are 200 pages.
When downloading, the images are numbered 00, 01, .... and image 100 overwrites 00, 101 overwrites 01, etc.
so volumes over 100 pages are not processed successfully.
Suggested fix: number with 3 digits instead of 2 :)

**Comment by izneo-get** [comment]
Si vous récupérez des BD en français, j'en déduis qu'on peut communiquer en français ?
(si ça pose un problème, je peux m'adapter)

Quelle commande avez-vous saisie ?
Le script est prévu pour regarder le nombre de pages attendues et de définir le nombre de chiffres à utiliser dans le nommage en fonction.

Par exemple, avec 
```
python izneo_get.py https://www.izneo.com/fr/bd/documentaire/l-affaire-des-affaires-465/l-enquete-1548
```
les images récupérées sont bien nommées "T2 - L'Affaire des affaires 000.jpg". Je n'arrive pas à reproduire le bug.

**Comment by ehanuise** [comment]
Oui, pas de problème pour le Français :-)
Effectivement le problème ne se pose pas sur le tome 2, mais il est présent sur le tome 1 
la commande que j'utilise :

`python izneo_get.py --no-tree --output-format cbz  https://www.izneo.com/fr/bd/documentaire/l-affaire-des-affaires-465/l-argent-invisible-947`

Je vois aussi que le script détecte 48 pages sur le tome 1 et 200 sur le T2. J'en déduis qu'il adapte dynamiquement son numérotage ## ou ### en fonction de ce qu'il détecte ?
Peut-être est il préférablme de toujours utiliser ### plutôt que ## ou ### dynaiquement ?

(NB je suis très impressionné par votre réactivité :-) Merci! )

**Comment by izneo-get** [comment]
OK, je vois le problème.
Dans la page
https://www.izneo.com/fr/bd/documentaire/l-affaire-des-affaires-465/l-argent-invisible-947
ils annoncent que le tome fait 48 pages.
J'avais déjà pris une marge de quelques pages. Or là, la différence est trop importante.
On ne peut pas faire confiance à Izneo !

Je rajoute un digit à tous les coups car je ne vois pas comment régler le problème plus simplement.

Disponible dans adb8ecc..e0d7ae4

**Comment by ehanuise** [comment]
Oui effectivement, le nombre de pages détecté est parfois fantaisiste. Avec 3 digits ca devrait couvrir la grosse majorité des cas :-)
Merci et bonne soirée!

**Comment by izneo-get** [comment]
Nos messages se sont croisé 😄 

Je vous invite à tester l'option "--webp 70" qui permet de réduire considérablement la taille des images pour une qualité quasi identique.
(si votre lecteur de BD est compatible, bien sûr)

**Comment by ehanuise** [comment]
Merci :)
