### ISSUE TITLE
Unexpected character after line continuation character ?

### ISSUE THREAD

**Issue by StarFlore** [izneo-get/izneo-get#40]
Quand je veux télécharger un album j'ai ce message d'erreur qui s'affiche : unexpected character after line continuation character
Que faut-il faire pour résoudre ce problème ?
![2022-08-15 (2)](https://user-images.githubusercontent.com/111277671/184635535-c0516d56-2338-4a38-8c14-32f4d91c80d6.png)
?

**Comment by izneo-get** [comment]
Quelle ligne de commande avez-vous exécuté ?
On dirait que vous avez lancé la commande 
`python`
et ensuite 
`izneo_get.py URL`

Pour faire fonctionner le script, il faut exécuter dans la même commande : 
`python izneo_get.py URL`

**Comment by StarFlore** [comment]
En rajoutant la commande python, ça m'affiche "invalid syntax". Où est mon erreur 
![2022-08-15 (4)](https://user-images.githubusercontent.com/111277671/184645777-4e149f96-a95b-4d6a-acb1-6b2ab78307a0.png)
?

**Comment by izneo-get** [comment]
J'ai l'impression que vous tapez ça dans une console python. 
Il faut exécuter la commande dans une invite de commande. 
Pour lancer une invite de commande, il faut par exemple taper `cmd` dans la recherche de Windows.

**Comment by StarFlore** [comment]
J'ai bien suivi vos conseils. J'ai maintenant une erreur au niveau de la ligne 67 qui s'affiche, que faire ?
![2022-08-15 (6)](https://user-images.githubusercontent.com/111277671/184651214-c746216c-7126-458b-a459-69030de8bcca.png)
