### ISSUE TITLE
Problème avec izneo_list

### ISSUE THREAD

**Issue by Mahora2106** [izneo-get/izneo-get#41]
Bonjour,
Lorsque je fais la commande python izneo_list.py cela ne fonctionne pas je n'ai pas la liste de tous les chapitres ou tomes de la série.
Avant ça marchait, je ne pense pas avoir fait quelque chose qui ne fallait pas

**Comment by izneo-get** [comment]
Je viens de mettre à jour : 3795b46

Il n'est désormais plus possible d'obtenir une liste de liens d'albums en faisant une recherche par mot clé. 
La recherche par mot clé retourne désormais les URL des séries qui correspondent au mot clé (comme l'option `--series` précédemment).
Une fois qu'on a trouvé l'URL de la série qui nous intéresse, on peut relancer la commande mais avec l'URL en paramètre.

Exemple : 
`python izneo_list.py asterix` 
retourne : 
```
# Astérix
https://www.izneo.com/fr/bd/action-aventure/asterix-5841
# Les 12 Travaux d'Astérix
https://www.izneo.com/fr/bd/action-aventure/les-12-travaux-d-asterix-42992
# Ratafia Delirium
https://www.izneo.com/fr/bd/humour/ratafia-delirium-28020
# Spirou et Fantasio - Hors-série
https://www.izneo.com/fr/bd/humour/spirou-et-fantasio-hors-serie-12333
...
```

Pour avoir la liste des albums d'Asterix, il faut exécuter la commande : 
`python izneo_list.py https://www.izneo.com/fr/bd/action-aventure/les-12-travaux-d-asterix-42992`

**Comment by Mahora2106** [comment]
Bonjour ça ne marche toujours pas pour moi, ça n'affiche rien du tout et j'ai pourtant tout retéléchargé.
![image](https://user-images.githubusercontent.com/71670560/190964183-3852ab26-8060-4076-bb75-70475b2aab14.png)

**Comment by izneo-get** [comment]
Je viens de voir qu'il y a 2 types d'albums chez Izneo : "volumes" et "others". 

Dans la version 8d8c3e7 le script gère les 2. 

La commande
`python izneo_list.py https://www.izneo.com/fr/bd/action-aventure/les-12-travaux-d-asterix-42992`

retourne désormais : 
```
# Les 12 Travaux d'Astérix - Les 12 Travaux d'Astérix (*)
https://www.izneo.com/fr/bd/action-aventure/les-12-travaux-d-asterix-42992/les-12-travaux-d-asterix-15076
```

**Comment by Mahora2106** [comment]
Alors ça l'air de marcher pour les mangas, mais par contre cela ne marche toujours pas pour les webtoons apparemment. Vraiment désolée

**Comment by izneo-get** [comment]
Pouvez-vous me donner un exemple qui ne fonctionne pas ?

**Comment by izneo-get** [comment]
Il existe donc un autre type `chapters`. 
Je l'ai rajouté dans 69d6b9f

Dites-moi si tout est OK.

**Comment by Mahora2106** [comment]
Super ça marche merci beaucoup.
