### ISSUE TITLE
Récupération des métadonnées dans un fichier xml

### ISSUE THREAD

**Issue by Spiralo-Idioide** [izneo-get/izneo-get#43]
Bonjour,

Déjà merci pour l'outil et tout ce qu'il permet de faire. 
Du coup je me demandai si il était possible d'ajouter une fonctionnalité qui permettrait de récupérer les infos (Genres, auteurs, résumé, éditeur...) et de les ajouter soit dans le titre soit dans un fichier xml, voir les 2 à la fois.

Et même également un outil qui récupérerait uniquement ces métadonnées pour éviter d'avoir à télécharger à nouveau toutes les images.

Voilà tout pour moi et encore merci pour l'outil

**Comment by izneo-get** [comment]
Bonjour,
Dans la version 09b2381 j'ai rajouté un nouveau script : `izneo_infos.py`
Il permet de récupérer les informations d'une BD et les enregistrer dans un fichier JSON. 

Exemple d'utilisation : 
```
python izneo_infos.py --output assassination-classroom-t1.json https://www.izneo.com/fr/manga-et-simultrad/shonen/assassination-classroom-4744/assassination-classroom-t1-19197
```

Si vous mettez un fichier avec l'extension ".xml", c'est au format XML que le fichier sera enregistré. 

Cela répond-il à votre besoin ?

**Comment by Spiralo-Idioide** [comment]
Pour moi c'est nickel, merci beaucoup, vraiment. C'était super rapide.
