### ISSUE TITLE
izneo_list

### ISSUE THREAD

**Issue by gjafh** [izneo-get/izneo-get#47]
Hi,

Thank you very much for this great project. Finally, I have a solution to make a backup of my library. 

I have a strange issue with izneo_list, It does not matter what I try, it does not give any rellevant output. Izneo_get works great but adding every album manually to a list is a lot of work.

I hope this error is resolvable.

Kind regards,

Gerrit Jan Hoogeland

**Comment by izneo-get** [comment]
Hello!

If you run
```
python izneo_list.py https://www.izneo.com/fr/bd/humour/lucky-luke-dupuis-988
```
what is the output?

On my side it looks like:
```
# Lucky Luke (Dupuis) - [31] Lucky Luke - Tome 31 - Tortillas pour les Dalton
https://www.izneo.com/fr/bd/humour/lucky-luke-dupuis-988/lucky-luke-tome-31-tortillas-pour-les-dalton-2209
# Lucky Luke (Dupuis) - [30] Lucky Luke - Tome 30 - CALAMITY JANE
https://www.izneo.com/fr/bd/humour/lucky-luke-dupuis-988/lucky-luke-tome-30-calamity-jane-2210
# Lucky Luke (Dupuis) - [29] Lucky Luke - Tome 29 - DES BARBELES SUR LA PRAIRIE
https://www.izneo.com/fr/bd/humour/lucky-luke-dupuis-988/lucky-luke-tome-29-des-barbeles-sur-la-prairie-2211
...
```

If I save the output in an UTF-8 text file (eg. "lucky.txt"), I download all items of the text files providing the path instead of the URL.

**Comment by gjafh** [comment]
Hi,

If I run the provided command, I receive the same output. I think the problem may be that I have bought a set of Dutch albums that are not listed on the general site:

This command:
 python3 izneo_list.py https://www.izneo.com/fr/bd/historique/robbedoes-door-12052

does not give a valid output. The URL gives a 404 even. In my library the link is:
https://www.izneo.com/fr/bibliotheque/detail/robbedoes-door-12052
this gives a page with all the albums.

Kind regards,
Met vriendelijke groet,

Gerrit Jan Hoogeland

--
+31 (6) 295 44 174
***@***.***

Op 10 sep. 2023, om 17:53 heeft izneo-get ***@***.***> het volgende geschreven:



Hello!

If you run

python izneo_list.py https://www.izneo.com/fr/bd/humour/lucky-luke-dupuis-988


what is the output?

On my side it looks like:

# Lucky Luke (Dupuis) - [31] Lucky Luke - Tome 31 - Tortillas pour les Dalton
https://www.izneo.com/fr/bd/humour/lucky-luke-dupuis-988/lucky-luke-tome-31-tortillas-pour-les-dalton-2209
# Lucky Luke (Dupuis) - [30] Lucky Luke - Tome 30 - CALAMITY JANE
https://www.izneo.com/fr/bd/humour/lucky-luke-dupuis-988/lucky-luke-tome-30-calamity-jane-2210
# Lucky Luke (Dupuis) - [29] Lucky Luke - Tome 29 - DES BARBELES SUR LA PRAIRIE
https://www.izneo.com/fr/bd/humour/lucky-luke-dupuis-988/lucky-luke-tome-29-des-barbeles-sur-la-prairie-2211
...


If I save the output in an UTF-8 text file (eg. "lucky.txt"), I download all items of the text files providing the path instead of the URL.

**Comment by izneo-get** [comment]
If the aim is to get all the albums of your library, I've added a new feature for you in commit 688b67b72f8348dec76c0e0bd0826d6edd4ad7d4

Please update then run:
```
python izneo_list.py --session-id YOURSESSIONID bibliotheque
```
(replacing `YOURSESSIONID` with your actual session id)

Whith this keyword, it will make a list of all your purchased albums. 

Tell me if it's OK.

**Comment by gjafh** [comment]
Wow,

That works like a charm. Can I pay you a bottle of wine?

Met vriendelijke groet,

Gerrit Jan Hoogeland

--
+31 (6) 295 44 174
***@***.***

Op 10 sep. 2023, om 19:21 heeft izneo-get ***@***.***> het volgende geschreven:



If the aim is to get all the albums of your library, I've added a new feature for you in commit 688b67b<https://github.com/izneo-get/izneo-get/commit/688b67b72f8348dec76c0e0bd0826d6edd4ad7d4>

Please update then run:

python izneo_list.py --session-id YOURSESSIONID bibliotheque


(replacing YOURSESSIONID with your actual session id)

Whith this keyword, it will make a list of all your purchased albums.

Tell me if it's OK.

**Comment by izneo-get** [comment]
OK, now with commit 99e3a4bd35cdafbfe302835dfb2eea8d14f899d7 you should even be able to list from your library, filtering on a specific serie:
```
python izneo_list.py https://www.izneo.com/fr/bibliotheque/detail/robbedoes-door-12052
```

> Can I pay you a bottle of wine?

Do you have crypto-wine to be sent in the blockchain ? >_<

**Comment by gjafh** [comment]
Also a great option, thanx.

Maybe a PayPal account that you use?

Met vriendelijke groet,

Gerrit Jan Hoogeland

--
+31 (6) 295 44 174
***@***.***

Op 10 sep. 2023, om 21:05 heeft izneo-get ***@***.***> het volgende geschreven:



OK, now with commit 99e3a4b<https://github.com/izneo-get/izneo-get/commit/99e3a4bd35cdafbfe302835dfb2eea8d14f899d7> you should even be able to list from your library, filtering on a specific serie:

python izneo_list.py https://www.izneo.com/fr/bibliotheque/detail/robbedoes-door-12052


Can I pay you a bottle of wine?

Do you have crypto-wine to be sent in the blockchain ? >_<

**Comment by izneo-get** [comment]
I don't really want to associate a PayPal account (with my identity) with the kind of repos I own with this account 😄
