### ISSUE TITLE
Parfois izneo_infos ne télécharge pas toutes les métadonnées

### ISSUE THREAD

**Issue by Spiralo-Idioide** [izneo-get/izneo-get#51]
Bonjour,

Je me suis rendu compte que pour certaines BD certaines infos n'étaient parfois pas récupérées par izneo_infos. Je suis en version 1.0.1

J'ai rencontré plusieurs exemples mais actuellement le seul que j'ai sous la main est :
 [https://www.izneo.com/fr/abo/bd/humour/les-tuniques-bleues-956/les-tuniques-bleues-tome-12-les-bleus-tournent-cosaques-2104](https://www.izneo.com/fr/abo/bd/humour/les-tuniques-bleues-956/les-tuniques-bleues-tome-12-les-bleus-tournent-cosaques-2104)

Malgré la présence de l'ensemble des informations sur la page. 
Les champs `title`, `subtitle`, `serie_name`, `volume`, `shelf_name`, `gender_name`, `readDirection` et `synopsis` ne sont pas téléchargés. Ça fonctionne sur les autres albums de la série.

```
> python izneo_infos.py 'https://www.izneo.com/fr/abo/bd/humour/les-tuniques-bleues-956/les-tuniques-bleues-tome-12-les-bleus-tournent-cosaques-2104'

Genres               : Humour | Jeunesse
Auteurs              : Lambil | Raoul Cauvin
Editeur              : Dupuis
Numéro               : 12/68
Paru le              : 15/06/2012
Public               : Tout
Modes de Lecture     : HD eazyComics

```

Je sais que pour d'autres BD le problème était sur les auteurs. Je suis actuellement en train de refaire des tests pour retrouver d'autres exemples.

Cordialement et merci pour l'outil, le téléchargement fonctionne parfaitement. Notamment la parallélisation qui est incroyable.

**Comment by izneo-get** [comment]
Malheureusement, c'est l'API de Izneo qui ne retourne pas la bonne valeur. 
L'identifiant de cette BD est `2104`. 
Si on appelle l'URL 
```
https://www.izneo.com/book/2104
```
on obtient (à l'heure où j'écris ce post) : 
```
{"data":"Votre album semble rencontrer un probl\u00e8me, nous vous prions de nous excuser pour la g\u00eane occasionn\u00e9e. Nos \u00e9quipes mettent tout en oeuvre pour rendre accessible votre album le plus rapidement possible.","code":8,"status":"error"}
```
alors que ça devrait retourner les informations de la BD.

Si je clique sur la BD pour essayer de la lire, je suis redirigé sur l'URL 
```
https://www.izneo.com/fr/bd/humour/les-tuniques-bleues-956/les-tuniques-bleues-tome-12-les-bleus-tournent-cosaques-2104/read
```
et je n'obtiens pas la BD, mais un message d'erreur : 
```
Un signalement a été envoyé

Votre album semble rencontrer un problème, nous vous prions de nous excuser pour la gêne occasionnée. Nos équipes mettent tout en oeuvre pour rendre accessible votre album le plus rapidement possible.
[Fermer]
```

De mon côté, je ne peux malheureusement rien faire : c'est la BD qui est indisponible.

**Comment by Spiralo-Idioide** [comment]
Ok j'ai trouvé le truc. Il semblerait que pour certaines BD certaines infos ne sont disponibles dans l'API que si on est connecté et qu'on a accès à la BD (acheté ou abonnement). 
Il semblerait également que l'impossibilité d'accéder à l'aperçu soit corroboré avec l'impossibilité 


Du coup j'imagine qu'une option permettant à `izneo_infos` d'utiliser l'id de session du cache pourrait peut-être fonctionner ?

Bon après c'est loin d'être un problème majeur. Il semblerait que ça arrive 5% du temps environ max. `izneo_get` lui fonctionne à chaque fois et c'est ça le plus important.

**Comment by izneo-get** [comment]
Si vous remplissez l'identifiant de session et que vous utilisez `izneo_get` avec l'option "récupérer juste les infos" pour l'URL
```
https://www.izneo.com/fr/bd/humour/les-tuniques-bleues-956/les-tuniques-bleues-tome-12-les-bleus-tournent-cosaques-2104/read
```
Est-ce que ça fonctionne ? 
(je n'ai pas d'abonnement, je ne peux donc pas vérifier)

**Comment by Spiralo-Idioide** [comment]
J'ai essayé avec l'id de session d'un compte avec abonnement et d'un autre compte sans abonnement. 
Il semblerait que ça fasse bel et bien une différence. 

**Avec abonnement :**
```
[?] What parameter do you want to update: >> DONE <<
   Output folder: DOWNLOADS/{serie}
   Filename pattern: {title} - {volume}. {subtitle}
   Image format: ORIGIN
   Image quality: 100
   Output format: CBZ
   Pause (sec): 1
   User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
   Continue from existing: True
   Authentication from cache: True
   Save this config as default
 > >> DONE <<

[?] What do you want to do?: Get book infos only
   Download + Convert + Pack
 > Get book infos only
   Download book only
   Convert book only
   Pack book only
   EXIT

URL: https://www.izneo.com/fr/bd/humour/les-tuniques-bleues-956/les-tuniques-bleues-tome-12-les-bleus-tournent-cosaques-2104
Session ID (value of cookie named "c03aab1711dbd2a02ea11200dde3e3d1"): <session id avec abo>
{title}: Les Tuniques Bleues
{pages}: 46
{serie}: Les Tuniques Bleues
{volume}: 12
{genre}: Humour
{subtitle}: Les Tuniques Bleues - Tome 12 - Les bleus tournent cosaques
{isbn}: 9782800108698
{language}: fr
{read_direction}: LTOR
Done!
```


**Sans abonnement :**

```
[?] What parameter do you want to update: >> DONE <<
   Output folder: DOWNLOADS/{serie}
   Filename pattern: {title} - {volume}. {subtitle}
   Image format: ORIGIN
   Image quality: 100
   Output format: CBZ
   Pause (sec): 1
   User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
   Continue from existing: True
   Authentication from cache: True
   Save this config as default
 > >> DONE <<

[?] What do you want to do?: Get book infos only
   Download + Convert + Pack
 > Get book infos only
   Download book only
   Convert book only
   Pack book only
   EXIT

URL: https://www.izneo.com/fr/bd/humour/les-tuniques-bleues-956/les-tuniques-bleues-tome-12-les-bleus-tournent-cosaques-2104
Session ID (value of cookie named "c03aab1711dbd2a02ea11200dde3e3d1"): <session id sans abo>
Traceback (most recent call last):
  File "/home/user/tools/izneo-get/izneo_get.py", line 5, in <module>
    __main__.main()
  File "/home/user/tools/izneo-get/izneo_get/__main__.py", line 76, in main
    save_path = action_infos_and_download(url, config, do_download, forced_title)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/izneo-get/izneo_get/__main__.py", line 45, in action_infos_and_download
    infos = processor.get_book_infos()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/izneo-get/izneo_get/plugins/izneo.py", line 266, in get_book_infos
    title = clean_attribute(book_infos["title"])
                            ~~~~~~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'

```

**Comment by izneo-get** [comment]
Merci pour cette confirmation. 

Je mets quand même à jour le fait de mettre des valeurs par défaut à vide plutôt que planter quand il n'y a pas d'infos sur le livre.
