### ISSUE TITLE
Est il possible de télécharger une version easycomics ?

### ISSUE THREAD

**Issue by prahal** [izneo-get/izneo-get#57]
La lecture vignette par vignette (easycomics) est très bien pour les albums qui la supporte.
Serait t'il possible de l'ajouter ?
"titre - easycomics/"
"titre - easycomics.cbz"

**Comment by izneo-get** [comment]
Bonjour, 
Je ne suis pas sur de comprendre la demande. Vous voulez que le titre du fichier contienne automatiquement le mot "easycomics" quand c'est un livre de type "easycomics" ?

Ou vous souhaitez que le script puisse télécharger image par image quand c'est possible ?
Dans ce cas, vous pouvez tester [Comic-Slicer](https://www.comic-slicer.net) qui permet de soit découper les cases de n'importe quelle BD ou bien de proposer un lecteur HTML façon "easycomics" (mais bien plus pratique). 
Exemple de rendu : https://www.comic-slicer.net/demo/index.html

**Comment by prahal** [comment]
Je voulais la possibilité de télécharger image par image.
Je vais regarder Comic-Slicer. par contre je suppose que les images individuelles des albums supportant "easycomics" sur izneo sont scannée en plus haute résolution. Mais peut être que les images découpées des planches sont suffisantes. Merci.
Je rouvrirais si la résolution des planches découpées est trop basse.

Par contr je suppose que Comic-Slicer ne génère pas un cbz mais des jpegs individuels ?
Pour le lecteur html, il s'agit de lire sous Android la plupart du temps (car izneo a tendance à se déconnecter quand je suis en trajet sans internet et je ne peux plus accéder aux contenus car il me demande de me logger via internet d'abord. Il est possible que le problème soit corrigé depuis car je n'ai pas réussi à le reproduire ce mois ci en coupant internet de façon artificielle mais début novembre j'ai encore eu le problème).

**Comment by izneo-get** [comment]
Comic-Slicer permet de récupérer un fichier ZIP avec toutes les images. Elles sont correctement numérotées, ce qui fait qu'il suffit de renommer le fichier en ".CBZ" pour que ça soit compatible avec n'importe quel application de comics. 

Comic-Slicer permet aussi de générer une sorte de site web avec son player embarqué. Les images ne sont pas découpées, mais sont zoomées dynamiquement pour s'adapter aux cases. Il suffit de dézipper l'archive sur son téléphone / sa tablette et on peut utiliser le player avec n'importe quel navigateur en étant hors ligne en ouvrant le fichier "index.html". 
Personnellement je trouve ça super agréable à utiliser.
