### ISSUE TITLE
invalid fixup in master - spurious extension removal from directory name

### ISSUE THREAD

**Issue by prahal** [izneo-get/izneo-get#58]
https://github.com/izneo-get/izneo-get/commit/6e2f44e1bc9b889faec80d3f001596aa1317ecd3 replace strip(".cbz") by a ".zip" removal.
But save_path is a directory, not a file so I do not expect it to have a zip extension.
In #55 I removed the strip("é.cbz") which to me is a bug that had no effect in most cases (as it only removed start and trailing '.', 'c', 'b' and 'z' characters from the directory name.
Did your initial intent was to remove the ".zip" extension from the directory where you download the images?

**Comment by izneo-get** [comment]
>  Did your initial intent was to remove the ".zip" extension from the directory where you download the images?

Probably...
But it's useless.
