### ISSUE TITLE
Impossible d'obtenir une BD complète ([WARNING] Page XX inaccessible)

### ISSUE THREAD

**Issue by lowtekluldo** [izneo-get/izneo-get#6]
Bonjour,
je viens de découvrir ce script (merci de l'avoir créé) mais en essayant de récupérer des BD, je finis toujours par obtenir une page inaccessible qui achève le téléchargement par la même occasion.
Visiblement, d'après l'_issue_ précédent, cela serait dû à un problème de cookie donc j'ai tenté de les mettre à jour avec les infos de cookie d'un autre navigateur mais rien n'y fait...
J'envoie les infos de cookie dans le fichier izneo_get.cfg à partir de votre modèle.
Les BD que j'essaye de récupérer font bien partie de ma bibliothèque.

Est-ce un bug ou un mauvais paramétrage de ma part ?
Merci.

EDIT : En mettant mon _cfduid_ et ma _session_id_ en arguments dans ma ligne de commande, ça fonctionne... Mon fichier _izneo_get.cfg_ est pourtant bien dans le même répertoire que _izneo_get.py_... Je sèche sur ce qui ne fonctionne pas avec le .cfg mais au moins, je peux l'utiliser en ligne de commande.

![image](https://user-images.githubusercontent.com/59918084/77960640-f4930680-72d8-11ea-96e1-cf147c4959e5.png)

![image](https://user-images.githubusercontent.com/59918084/77960495-b1389800-72d8-11ea-9399-5feb1de93212.png)

**Comment by izneo-get** [comment]
Bonjour,

Pouvez-vous me confirmer que vous mettez à jour le fichier "izneo_get.cfg" qui se trouve dans le même répertoire que "izneo_get.py" (et non pas celui qui est dans le répertoire "bin") ?

Pouvez-vous tester avec l'option "--config [chemin du fichier de conf]" afin de vérifier que c'est le bon fichier utilisé ? (parfois il y considère que le répertoire local est "Roaming" de Windows).
```
python izneo_get.py --config "c:\izneo-get-master\izneo_get.cfg" "https://www.izneo.com/fr/bd/fantastique/carthago-5276/l-abime-regarde-en-toi-62971"
```

En fait, en regardant attentivement votre capture d'écran, je constate que vous êtes dans le répertoire de "python.exe" et que vous appelez le script "izneo_get.py" avec son chemin complet. Je pense que le script cherche le fichier "izneo_get.cfg" dans le répertoire de "python.exe" (celui où vous êtes).
Pouvez-vous tester de vous mettre dans le répertoire du script et d'appeler python.exe avec son chemin complet ?

**Comment by izneo-get** [comment]
J'ai fait une évolution qui devrait corriger ce problème.
Je vous invite à mettre à jour et retester.

**Comment by lowtekluldo** [comment]
Bonjour,

merci pour votre retour rapide. :)
En effet, la mise à jour a bien solutionné le problème. Mon utilisation est peut-être peu orthodoxe mais je ne fais pas du tout de Python donc j'ai sûrement un usage inattendu de la part de quelqu'un d'aguerri.

En tout cas, votre script m'a malheureusement permis de me rendre compte que certains ebooks sont vraiment limite niveau qualité pour de l'officiel...

Merci encore pour la solution rapide et le temps consacré à izneo-get. :)

**Comment by izneo-get** [comment]
> En tout cas, votre script m'a malheureusement permis de me rendre compte que certains ebooks sont vraiment limite niveau qualité pour de l'officiel...

Vous avez un exemple ?
Je trouve que la qualité est plutôt bonne (sur les tomes que j'ai récupérés).

**Comment by lowtekluldo** [comment]
Oui, j'ai récupéré pas mal de mangas Kazé qui ont les 3 premiers tomes gratuits en ce moment et la résolution des JPEG est bloquée à 1200x1884 en 96 dpi, ce qui est peu pour lire sur ma Fire HDX qui a une résolution supérieure (1600x2560), l'image est quand même bien upscalée...
Par exemple, j'envisageais de continuer le manga The Promised Neverland en numérique plutôt qu'en papier et ça m'a refroidi... Vous pouvez essayer le 1er tome qui est gratuit en ce moment par exemple : https://www.izneo.com/fr/manga-et-simultrad/shonen/the-promised-neverland-10633/the-promised-neverland-t01-27641

L'avantage d'izneo-get, c'est que, comme il permet de télécharger les 1res pages même quand le livre ne fait pas partie de la bibliothèque, ça permet de "tester" la qualité pour voir si elle correspond aux attentes ou pas car en effet, chez d'autres éditeurs, c'est beaucoup mieux et parfait pour ma tablette.

**Comment by izneo-get** [comment]
Astuce : pour récupérer plusieurs tomes, vous pouvez mettre les URL dans un fichier ".txt" et mettre ce fichier dans la ligne de commande.

**Comment by lowtekluldo** [comment]
Oui, merci, je l'avais vu dans la doc et essayé. En effet, c'est bien pratique comme fonctionnalité. :)
