### ISSUE TITLE
Total pour la barre de progression

### ISSUE THREAD

**Issue by sholine** [izneo-get/izneo-get#62]
Hello !
J'ai remarqué un bug sur la barre de progression qui fait qu'on ne voit pas la barre en tant que telle, car le nombre total d'item n'est pas renseigné (étrange car tqdm pourrait directement prendre la taille de l'enumerate qu'il prend en paramètre...)
Mais on peut corriger le problème en ajoutant un paramètre "total" en paramètre de tqdm dans le fichier site_processor.py (vers la ligne 178) :
`total=len(book_infos.page_urls),`
Et ça fonctionne nickel.
J'ai voulu faire une PR mais ce n'est pas autorisé ! 😉

**Comment by sholine** [comment]
Et au fait bravo pour les dernières améliorations sur la gestion de la conf en ligne de commande et du cookie de session, c'est top !

**Comment by izneo-get** [comment]
C'est étrange, car dans la version qui télécharge en asynchrone la barre de progression s'affiche correctement sans qu'on lui précise la taille...

Merci pour la suggestion de FIX. Je l'ai rajoutée en [3070e84](https://github.com/izneo-get/izneo-get/commit/3070e84ee6a3f0971bc8ac0f8425cdb395fc3f11)


Pour information, le fait de mettre "0" comme pause entre 2 pages permet de télécharger en asynchrone, et donc avoir les pages **beaucoup** plus rapidement.
