### ISSUE TITLE
Retirer le dossier bin/ dans le l'historique de git?

### ISSUE THREAD

**Issue by sbourlon** [izneo-get/izneo-get#63]
Bonjour,

Merci pour ce projet!

Le repository est très long à télécharger parce que l'historique git contient un gros dossier `bin/`.

Bien qu'il soit possible d'éviter ce problème avec l'option `--depth 1`, peut-être serait-il mieux de supprimer ce dossier de l'historique de git?

Les fichiers en questions:

```
805fd953b35f  9.7MiB bin/chromedriver88.exe
d51602de7fe0   10MiB bin/chromedriver89.exe
1d6573bf19f2   23MiB bin/izneo_get.zip
c18f88cd8728   23MiB bin/izneo_get.exe
d3d64003243a   24MiB bin/izneo_get.exe
dac50ff9f164   24MiB bin/izneo_get.exe
3ac3b437349c   24MiB bin/izneo_get.exe
e838d5b44781   28MiB bin/izneo_get_selenium.exe
c51b5499d197   28MiB bin/izneo_get_selenium.exe
3ce8da436751   28MiB bin/izneo_get_selenium.exe
385fad6e505b   28MiB bin/izneo_get_selenium.exe
7764b6611229   28MiB bin/izneo_get_selenium.exe
be9b07daf388   30MiB bin/izneo_get_selenium.exe
1837f3c5c6e9   30MiB bin/izneo_get.exe
```

Le script pour obtenir cette liste: https://stackoverflow.com/questions/10622179/how-to-find-identify-large-commits-in-git-history

**Comment by izneo-get** [comment]
Sous Windows, avec Gitbash : 
- Je trouve mon fichier de pack avec 

```
ls .git/objects/pack/*.idx
```

- Je repère les 20 fichiers les plus volumineux du pack avec

```
git verify-pack -v .git/objects/pack/<MON PACK>.idx | sort -k 3 -n | tail -n 20
```
La première colonne retourne l'identifiant SHA.

- Je regarde le fichier associé avec 

```
git rev-list --objects --all | grep <SHA>
```
qui retourne le chemin du fichier.

- Si c'est un fichier à supprimer, je le supprime de l'historique *depuis un repo propre* avec 

```
git filter-repo --path <CHEMIN DU FICHIER> --invert-paths
```

Si la commande est inconnue, je l'installe avec `pip install git-filter-repo`.

- Je mets à jour avec 
```
git reflog expire --expire=now --all
git gc --prune=now --aggressive
```

- Je force sur le repo distant
```
git push --force --all
git push --force --tags
```


Le repo devrait désormais être plus léger à cloner !

**Comment by sbourlon** [comment]
Super! Merci
