### ISSUE TITLE
[BUG] SyntaxWarning: invalid escape sequence '\d'

### ISSUE THREAD

**Issue by floviolleau** [izneo-get/izneo-get#64]
Hi,

Thanks for those amazing scripts.

I wrote back in the day some bash scripts to do almost the same thing and I'm happy to find someone who did the same :) <3

I tried yours and I have this warning:
``` bash
$ python izneo_list.py
/home/user/izneo-get/izneo_list.py:256: SyntaxWarning: invalid escape sequence '\d'
  id = re.findall(".+-(\d+)/", search)
/home/user/izneo-get/izneo_list.py:258: SyntaxWarning: invalid escape sequence '\d'
  id = re.findall(".+-(\d+)", search)
usage: izneo_list.py [-h] [--session-id SESSION_ID] [--config CONFIG] [--pause PAUSE] [--full-only] [--force-title] search
izneo_list.py: error: the following arguments are required: search
```

A quick search leads me to: https://stackoverflow.com/questions/50504500/deprecationwarning-invalid-escape-sequence-what-to-use-instead-of-d

Thanks!

**Comment by PhunkyBob** [comment]
What version of Python do you use?
What version of the script do you use?

I can't reproduce the problem, but I understand why it occurs. It should be fixed in 96ab41f4c4fb9f2e886f6a6d9350e1960b90f694·

**Comment by izneo-get** [comment]
What version of Python do you use?
What version of the script do you use?

I can't reproduce the problem, but I understand why it occurs. It should be fixed in 96ab41f4c4fb9f2e886f6a6d9350e1960b90f694·

**Comment by floviolleau** [comment]
Python: 3.12.3
izneo-get: master

**Comment by izneo-get** [comment]
Do you still have the problem after the fix?

**Comment by floviolleau** [comment]
Nope thanks!
