### ISSUE TITLE
Etendre à d'autres?

### ISSUE THREAD

**Issue by notna1109** [izneo-get/izneo-get#7]
Bonjour, je voulais savoir s'il était possible d'étendre le script à d'autres sites comparables à izneo comme par exemple cafeyn? Merci

**Comment by izneo-get** [comment]
Bonjour,
J'avais commencé à regarder pour Cafeyn, mais ils utilisent des techniques de DRM plus évolués. Pour l'instant, je n'ai pas de résultats satisfaisants permettant de les contourner. 
J'ai fait des outils pour Lizzie (malheureusement le service est actuellement interrompu) et Vimeo.

**Comment by notna1109** [comment]
Oui j'ai vu ce que tu as fait pour Lizzie et vimeo est top. Si tu arrive à contourner le truc pour Cafeyn ce serait top! Es-tu dessus ou as tu abandonné tout espoir d'avancer ?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by izneo-get** [comment]
Je m'y suis repenché à la lecture de votre précédent message au cas où une idée lumineuse me vienne. Mais non, rien n'est venu.
J'arrive laborieusement à faire à la main l'extraction des images page par page, mais je n'arrive pas à l'automatiser, même avec Selenium (une librairie qui permet de manipuler directement une instance du navigateur). 


Il me semble que SFR Presse va fusionner avec Cafeyn, on va voir si cela à un impact sur leur façon de présenter les choses.

**Comment by notna1109** [comment]
OK , je vois,

je vais demander à une connaissance de voir ce qu'il peut faire. Est-ce que dans l'intervalle vous pouvez partager le code? Comme cela la personne a qui je vais demander pourra se baser sur ce que vous avez deja fait?

Merci.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by izneo-get** [comment]
Malheureusement, pour l'instant je n'ai aucun code. 

Ma méthode est la suivante : 
- Utiliser Firefox.
- Ouvrir un magazine avec "Lire ce numéro".
- Sur la page courante, faire un clic-droit. Cela déclenche un message "Vous n'êtes pas autorisé à accéder à ce contenu", mais cela affiche néanmoins le menu du clic droit.
![](https://i.imgur.com/V6XB6RG.png)
- Avec Ctrl+clic sur "View image", on arrive à ouvrir l'image dans un nouvel onglet avec la qualité maximale. L'image a une URL de type "blob:null/111d3404-b39c-4c4c-95e9-7261308fbea8".
- Là, on peut enregistrer l'image sur le disque.
Et il faut recharger la page du magazine pour pouvoir aller à la page suivante.

Je n'arrive pas à automatiser la partie "clic-droit --> afficher l'image".
Il faudrait aussi que je trouve comment bloquer la fonction qui est effectuée lors du clic-droit. Il y a tellement de JS dans leur code, que je n'ai pas encore eu le courage de chercher où était cachée cette fonction et comment injecter du JS pour la surcharger.

**Comment by notna1109** [comment]
Bonjour

Merci, pour la procedure. Je vais voir comment on peut utiliser cela. Si j'arrive a faire quelque chose je vous en tiendrai informé.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by izneo-get** [comment]
Bonne nouvelle : j'ai réussi à créer un premier script qui permet d'extraire les images de Cafeyn !

C'est un peu plus contraignant (il faut ouvrir un navigateur Chrome en mode "debug" et il sera piloté par le script Python), mais ça fonctionne.

Je vous invite à aller voir ce repo : https://github.com/izneo-get/cafeyn-get
