### ISSUE TITLE
ERROR Impossible de trouver le livre

### ISSUE THREAD

**Issue by Baladash** [izneo-get/izneo-get#8]
Bonjour,

Déjà merci pour cet outil 👍 

Je ne parviens plus à télécharger les ebooks de ma bibliothèque, ça fonctionnait encore il y a 2 semaines.

Firefox et izneo_get sont à jour.

Mon izneo_get.cfg est bien à jour lui aussi et dans le même répertoire que izneo_get.py.

Que j'essaie sans le fichier de config et avec ou sans liste c'est pareil :

Cette BD n'est pas disponible dans l'abonnement
ERROR Impossible de trouver le livre

Idem sur des comptes différents et avec des ebooks téléchargés précédemment.

Avez-vous ce problème ?

Cdt.

**Comment by lowtekluldo** [comment]
Bonjour,
oui, même erreur chez moi sur des livres de ma bibliothèque que j'ai déjà téléchargés précédemment avec l'outil... :'(
J'espère que ce n'est pas une grosse mise à jour des DRM.

**Comment by izneo-get** [comment]
C'est exactement ça : grosse mise à jour das DRM. Les images ne sont plus directement accessibles, mais gérées par webkitSubtle. 

J'ai créé un nouveau script "izneo_get_selenium.py" qui utilise une méthode détournée pour récupérer les images, en se basant sur la librairie Selenium qui pilote un driver Chromium. 

Je vous invite à faire un _pull_ du projet, tester et me faire vos retours. 
Il vous faudra récupérer les drivers Chromium en fonction de votre version de Chrome présente sur votre ordinateur. 

Au passage, une légère modification : 
- L'option "--no-tree" n'existe plus est est considérée comme l'option par défaut. Il faut utiliser la nouvelle option "--tree" pour forcer la création d'arborescence.

**Comment by orwell-was-right** [comment]
J'avais ma propre version en bash avant qu'Izneo ne crypte ses livres. Du coup, elle ne marchait plus non plus et j'en ai fait une autre sur NodeJS qui fonctionne avec les nouvelles restrictions:

https://github.com/orwell-was-right/izneo-downloader

N'hésitez pas à me dire si cela fonctionne pour vous ou à vous en inspirer pour mettre à jour celle-ci

**Comment by izneo-get** [comment]
Bonjour,

Izneo-get est à jour depuis environ 1 mois ;)

**Comment by izneo-get** [comment]
J'avais oublié de le préciser dans ce ticket, ce qui fait que potentiellement des personnes intéressées auraient pu passer à côté de l'information. 
My bad...

**Comment by orwell-was-right** [comment]
> Bonjour,
> 
> Izneo-get est à jour depuis environ 1 mois ;)
> 
> Mais merci. Je regarderai quand il y aura de nouveaux changements qui me bloquent.

Zut je suis passé à côté. En même temps j'avais développé mon script avant de voir le tiens donc c'est pas grave 😬

J'en avais aussi un pour récupérer récursivement tout ce qui était dans l'abonnement dans la version précédente du site. Pas sûr qu'il fonctionne encore mais je peux vérifier et le publier si ça t'intéresse

**Comment by izneo-get** [comment]
Je ne suis personnellement pas intéressé n'étant pas collectionneur compulsif, mais tu peux mettre un lien vers ton script pour les utilisateurs susceptibles d'être intéressés.
