### ISSUE TITLE
Selenium

### ISSUE THREAD

**Issue by Baladash** [izneo-get/izneo-get#9]
Bonjour,

Je n'ai pas réussi à créer un Pull.

J'essaie d'utiliser la fonction izneo_get_selenium.py avec une liste, mais ça ne fonctionne pas :

line 319, in <module>
    driver.add_cookie({"name": "__cfduid", "value": cfduid, "domain": "izneo.com"})
line 894, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
line 321, in execute
    self.error_handler.check_response(response)
line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain

Avec une commande complète j'avance car l'ebook est reconnu, mais j'ai ce message :

line 612, in <module>
    rgb_im = im.convert("RGB")
AttributeError: 'NoneType' object has no attribute 'convert'

Cdt.

**Comment by izneo-get** [comment]
> Je n'ai pas réussi à créer un Pull.

La commande
```
git pull
```
ne fonctionne pas ?


Pouvez-vous me donner l'URL que vous essayez de télécharger ?
Il faudrait que j'arrive à reproduire l'erreur.
Est-ce que ce message arrive à la première image téléchargée ?

**Comment by izneo-get** [comment]
Concernant le problème lorsqu'on donne une liste d'URLs, j'ai corrigé dans le commit 8ebd7e5

**Comment by Baladash** [comment]
Non elle n'est pas reconnue.

Sur https://www.izneo.com/fr

Commande : izneo_get_selenium.py url -c cfduid -s session_id -o output_folder -f jpg
Peu importe l'url, j'ai le même message pour n'importe quel ebook de ma bibliothèque.

Aucune page n'est téléchargée, seul le total de pages de l'ebook reconnu est affiché :

Cette BD n'est pas disponible dans l'abonnement
Téléchargement de "xxx"
192 pages attendues
Destination : C:\xxx
Traceback (most recent call last):
  File "C:\xxx\Python\Python38-32\Tools\scripts\izneo_get_selenium.py", line 612, in <module>
    rgb_im = im.convert("RGB")
AttributeError: 'NoneType' object has no attribute 'convert'

Avec le Commit **8ebd7e5** j'arrive désormais à la même erreur que ci-dessus avec une liste 👍 

Cdt.

**Comment by izneo-get** [comment]
Pouvez-vous me donner toute la sortie ?
Par exemple : 
```
DevTools listening on ws://127.0.0.1:5620/devtools/browser/8948bbc8-432d-423e-a261-3aa9b7724a13
URL: https://www.izneo.com/fr/manga-et-simultrad/shonen/naruto-567/naruto-t1-1363
Cette BD n'est pas disponible dans l'abonnement
Téléchargement de "Naruto T1 - Tome 1-72 - Naruto T1"
192 pages attendues
Destination : c:\Temp/Naruto T1 - Tome 1-72 - Naruto T1
[page 22 / ~192] ...................... Waiting...

[ERROR] Impossible de récupérer la page 22
[WARNING] On a récupéré 22 pages (192 annoncées par l'éditeur)
OK
Terminé !
```

Voyez-vous bien un ligne du genre
```
DevTools listening on ws://127.0.0.1:5620/devtools/browser/8948bbc8-432d-423e-a261-3aa9b7724a13
```
?

Pouvez-vous tester avec l'exécutable ?
Quelle est la version du driver qui est utilisée ?


Ce qui m'étonne dans l'erreur 
```
 File "C:\xxx\Python\Python38-32\Tools\scripts\izneo_get_selenium.py", line 612, in
rgb_im = im.convert("RGB")
```
c'est que cette instruction n'est pas en ligne 612 mais en ligne 618.

**Comment by Baladash** [comment]
Alors avec l'exécutable c'est plus lent, mais ça fonctionne, je viens d'en télécharger un complet ! 👍 

Oui j'ai bien la ligne "DevTools listening on"

Je force la version 85 dans le izneo_get_selenium.cfg et version de Chrome : 85.0.4183.102.

En effet c'est bien la ligne 618 et non 612, j'ai dû mal copier/coller...

**Comment by Baladash** [comment]
Par contre avec l'exécutable je ne semble pas pouvoir utiliser de liste.

**Comment by izneo-get** [comment]
> Par contre avec l'exécutable je ne semble pas pouvoir utiliser de liste.

Vous utilisez bien celui du commit 8ebd7e5 ?


> Alors avec l'exécutable c'est plus lent, mais ça fonctionne, je viens d'en télécharger un complet !

Pouvez-vous faire un 
```
pip install -r requirements.txt
```
afin de vérifier que vous avez bien toutes les librairies nécessaires ?

**Comment by Baladash** [comment]
J'avais bien remplacé le izneo_get_selenium.exe, mais pas le izneo_get.exe et là ça fonctionne 👍 

Je viens de le faire, tout est bon sauf Numpy que j'ai installé à part, mais ça ne change pour l'erreur "ligne 618". Pour ce qui est de la lenteur, c'est mon impression, après ça fonctionne, c'est le principal.

Cdt.

**Comment by izneo-get** [comment]
Je vous confirme que cette nouvelle version est plus lente que la précédente. 
Il y a un navigateur web qui tourne en arrière plan qui simule la visualisation des pages 1 à 1.

**Comment by Baladash** [comment]
Petite MAJ : avec l'exécutable je ne peux pas télécharger en ligne de commande complète (bizaremment ça fonctionne pour "un" ebook, celui avec lequel j'avais testé bien sûr, mais pas avec les autres...), j'ai le même message qu'avec le izneo_get_selenium.py.

Par contre avec une liste ça télécharge, mais pas complètement, comme-ci les ebooks ne faisaient pas partie de ma bibliothèque :

[page 10 / ~201] ..........
[ERROR] Impossible de récupérer la page 10
[WARNING] On a récupéré 10 pages (201 annoncées par l'éditeur)

Pourtant le cfduid et le session_id sont à jour.

:/

**Comment by izneo-get** [comment]
Ce message d'erreur est typique du cas où les _cfduid_ et _session_id_ ne sont pas bons (le serveur refuse d'afficher les pages suivantes car il ne considère pas que vous avez un abonnement).

Vous donnez ces informations en ligne de commande ou dans le fichier de config ?

**Comment by Baladash** [comment]
Dans les fichiers de config.

Je viens de tester en ligne de commande, un coup ça marche pour un ebook, un coup ça ne marche pas pour un autre et j'ai l'erreur habituelle :

File "izneo_get_selenium.py", line 618, in <module>
AttributeError: 'NoneType' object has no attribute 'convert'

Dans une même série le tome 1 ne passe pas, mais le tome 2 passe...

Cdt.

**Comment by Baladash** [comment]
J'ai réussi à télécharger le tome 1 en l'incluant dans une liste qui cette fois-ci est passée... Je ne sais pas si c'est moi qui m'embrouille, mais c'est assez aléatoire, enfin on y arrive.

**Comment by izneo-get** [comment]
Je veux bien un lien qui ne passe pas en ligne de commande pour pouvoir tester.

**Comment by Baladash** [comment]
https://www.izneo.com/fr/manga-et-simultrad/seinen/lastman-5512/lastman-tome-1-4400 par exemple.

**Comment by izneo-get** [comment]
Pour moi, ce tome n'est pas inclus dans l'abonnement. Il est donc normal qu'il ne soit pas téléchargeable entièrement. 

Est-ce que c'est un manga que vous avez acheté ? 
Je n'ai pas de BD achetées sur Izneo, je ne peux donc pas tester si leur comportement est différent que ceux présents dans l'abonnement.

**Comment by Baladash** [comment]
Même sans avoir le tome dans la bibliothèque, on peut télécharger quelques pages, mais là rien puisqu'on a l'erreur line 618.

**Comment by izneo-get** [comment]
Pouvez-vous tester de sauver les images en WEBP ?
```
izneo_get_selenium.exe --webp 70 https://www.izneo.com/fr/manga-et-simultrad/seinen/lastman-5512/lastman-tome-1-4400
```

Dans le fichier _izneo_get_selenium.py_, en ligne 582, pouvez-vous remplacer 
```
                    canvas = driver.find_element_by_id("iz_canv")
                    if len(canvas.screenshot_as_base64) > 10000:
                        loaded = True
```
par
```
                    canvas = driver.find_element_by_id("iz_canv")
                    if len(canvas.screenshot_as_base64) > 10000:
                        print(canvas.screenshot_as_base64)
                        loaded = True
```
(rajout d'un "print" de debug) 
, exécuter le script python et coller ici le résultat ?

Je suis désolé, c'est difficile de débugger quand on n'arrive pas à reproduire le bug (j'ai testé sur 2 machines différentes).

**Comment by Baladash** [comment]
Je comprends, y'a pas de problème, c'est déjà sympa d'être disponible.

Je testerai ça demain, merci pour l'aide et bonne fin de soirée.

**Comment by Baladash** [comment]
Bonjour,

Alors j'ai retesté cette url avec ma commande.
Avec les mauvais identifiants, quelques pages sont téléchargés, avec les bons j'ai l'erreur "line 618, in <module>"...

En Webp ça télécharge complètement et plus vite j'ai l'impression.

J'ai modifié le izneo_get_selenium.py et lancé une commande, mais en résultat je n'ai qu'une chaîne de caractères illisible sur plusieurs lignes et à la fin :

line 619, in <module>
    rgb_im = im.convert("RGB")
AttributeError: 'NoneType' object has no attribute 'convert'

Cdt.

**Comment by izneo-get** [comment]
Pouvez-vous taper :
```
pip show Pillow
```
et me dire quelle version de Pillow vous utilisez ?

**Comment by Baladash** [comment]
Name: Pillow
Version: 7.2.0

**Comment by izneo-get** [comment]
OK !
Je suis en 6.2.1, et Pillow semble ne pas fonctionner de la même façon suite à l'upgrade.

Je suis passé en version 7 et j'arrive à reproduire le problème. 
J'ai corrigé dans le commit 11ef9910.

**Comment by Baladash** [comment]
OK, je testerai ça ce soir, cdt.

**Comment by Baladash** [comment]
Bonjour,

Ca a fonctionné direct avec izneo_get_selenium.py 👍 
En ligne de commande complète ou avec cfg et liste.

Ce qui est dommage outre la vitesse, c'est l'arborescence qui n'existe plus, "\fr\manga-et-simultrad\seinen\lastman" par exemple. Les noms des dossiers et des images diffèrent aussi d'avant, mais ce n'est pas plus gênant que ça.

Merci pour la résolution du problème de téléchargement 🥇 

Cdt.

**Comment by izneo-get** [comment]
Si vous souhaitez que l'arborescence soit créée, il suffit de mettre l'option 
```
--tree
```

J'ai enlevé le fait que l'arborescence soit créée par défaut, car on arrive très vite à la limite des 255 caractères autorisés par Windows et cela provoquait des erreurs difficiles à gérer.
